[step1] 문자열 사칙 연산 계산기
MalibinStudy/RacingCar pull request #13
Opened 2020-10-18 14:57 UTC by chaeppy

2020-10-19 02:06 UTC, nightmare73 requested changes
과제 하느라 고생 많았어~~ 😀

전반적으로 코드가 짧고 간결해서 가독성이 좋았어. 👍👍 하지만 한 클래스 또는 메서드가 너무 많은 일들을 하고 있는거 같아 그 책임을 분리해 보면서 리팩터링을 해보자.

논리적인 오류라는건 정말로 있을 수 없는 일에 대해서에 대한 에러가 나온다면 Exception을 발생시키는거야. 예를 들면, 문자열 계산기의 사칙기호는 / * + - 4개인데, 다른 #, $ 같은게 나오면 논리적으로 오류가 발생한 거잖아? 그래서 이럴 때는 계산값은 null 반환 이런게 아니라 아예 Exception을 발생시키는거지. null이면, 어떤게 어디서부터 잘못되었는지 모르잖아? 

지금은 "2 3" 입력시에 인덱스 바운드 Exception이 나타나네!! 이것도 바꿔 봅시다.

Calculator가 너무 많은 일들을 해서 클래스 분리도 해보고, 모두 public인걸 공개할 것만 공개하고, 숨겨둘 건 private으로 바꿔보자.

2020-10-19 02:06 UTC, malibinYun commented on src/main/kotlin/calculator/Calculator.kt
> +        }
메서드로 래핑하는 것 보단 그냥 쓰는게 더 가독성이 좋아보인다고 생각해!

2020-10-19 02:06 UTC, malibinYun commented on src/main/kotlin/calculator/Calculator.kt
> +    companion object {
모든 메서드가 다 static으로 설정되어있는데, 어떤 의도인지 잘 모르겠어.
전부 다 static으로 올리면 객체를 생성하지 않아도 메모리에 다 올라와 있는거라 아무래도 좋진 않다고 생각해.

2020-10-19 02:06 UTC, malibinYun commented on src/main/kotlin/calculator/Calculator.kt
> +        }
0으로 나눴을 때 예외 발생 굳굳!!! 👍👍
기본적으로 그냥 0으로 나눠봐도 0으로 나눌 수 없다는 Exception이 뜨긴 해서 여러모로 의견이 갈리는 구간이야.
기본제공이 있으니 안써줘도된다. VS 그래도 내가 걸러줘야한다.

2020-10-19 02:06 UTC, malibinYun commented on src/main/kotlin/calculator/Calculator.kt
> +        }
어떤게 null이고 공백문자열인지 알기 힘들거같아. 좀 더 구체적인 메서드명으로 바꿔보자.

2020-10-19 02:06 UTC, malibinYun commented on src/main/kotlin/calculator/Calculator.kt
> +        }
Exception 시 뭐가 이상한지 알려주는거 완전 잘했어 !! 결국 디버그를 위한거기 때문에 매우 좋은 습관이야

2020-10-19 02:06 UTC, nightmare73 commented on src/main/kotlin/calculator/Calculator.kt
> +
음 변수가 대문자로 시작하는데 Lint에 안걸리네.. 상수 자리여서그런가?
자바, 코틀린에서 절대 변하지 않을 상수 영역은 Snake case로 모두 대문자로 쓰는게 컨벤션이야.
```suggestion
        private val ARITHMETIC_OPERATIONS = listOf<String>("+", "-", "*", "/")

```

2020-10-19 02:06 UTC, nightmare73 commented on src/main/kotlin/calculator/Calculator.kt
> +        }
파라미터가 3개인데, 다른 설계로 3개짜리를 없애보는건 어떨까?

2020-10-19 02:06 UTC, nightmare73 commented on src/main/kotlin/calculator/Calculator.kt
> +    }
메서드 10줄 초과!
한 메서드에서 너무 많은 일들을 하고 있는거 같아. 더 잘게 쪼개보자.

2020-10-19 02:06 UTC, nightmare73 commented on src/test/kotlin/CalculatorTest.kt
> +    }
```suggestion
    @Test
    fun multiplyTest() {
        val multi = Calculator.multiply(3, 4)
        assertThat(multi).isEqualTo(12)
    }
```
이렇게 인라인으로 줄여도 괜춘할듯!

2020-10-19 02:06 UTC, nightmare73 commented on src/main/kotlin/calculator/Calculator.kt
> +            }
3 - 4 하는 경우에도 -1이 리턴될 수 있는데, else 에서 -1 이 리턴되면 디버깅이 어려워지지 않을까?
Exception을 던지는 건 어떨까?

2020-10-19 06:52 UTC, l2hyunwoo commented on src/main/kotlin/calculator/Calculator.kt
> +    companion object {
스태틱으로 올린 건 외부 클래스에서 이 멤버들에 접근할 수 있다는 건데, 외부에서 접근가능하다는 점에서 의도치 않은 오류가 이후에 발생할 수 있을 것 같아(물론 지금은 단일 클래스지만 클래스가 많아진다면 그럴 수도 있겠지)
그래서 외부에 공개해야하는 것 아니면 접근제어자를 거는게 좋다고 생각해

2020-10-19 07:06 UTC, l2hyunwoo reviewed
My Review Commit

2020-10-19 07:06 UTC, l2hyunwoo commented on src/main/kotlin/calculator/Calculator.kt
> +        }
코틀린에서 정수를 정수를 나눌 때 실제로 나눈 결과가 아니라 몫이 출력이 돼. 그래서 Operand들은 웬만하면 실수형으로 바꾸는게 좋을 것 같아

2020-10-19 07:06 UTC, l2hyunwoo commented on src/main/kotlin/calculator/Calculator.kt
> +        }
입력할 때 아무것도 입력 안 해도 "" String이 넘어오는데 그건 null이 아니니까 굳이 'String?' 타입으로 지정 안해줘도 될 것 같아. String?은 Null을 허용하니까 String으로 바꾸기만해도 오류 발생할 수 있는 가능성을 줄일 수 있을거야

2020-10-19 07:06 UTC, l2hyunwoo commented on src/main/kotlin/calculator/Calculator.kt
> +    }
Calculator는 연산을 처리하는 곳인데 이 부분은 연산에 직접적인 영향을 주기보단 연산을 도와주는 기능들을 하는 곳인 것 같으니 다른 클래스에서 처리하는 건 어떨까?

2020-10-20 06:16 UTC, SONPYEONGHWA reviewed
채원아 모든 코드들을 다 봐봤는데 잘하기도 했고 혁이형이랑 현우가 너무 잘 짚어줘서 남길 코멘트가 없다...ㅋㅋㅋㅋㅋㅋ고생했어~~

2020-10-20 07:09 UTC, chaeppy commented on src/main/kotlin/calculator/Calculator.kt
> +    companion object {
@nightmare73 
음.. 제가 이 멤버들을 static으로 짠건 Calculator 클래스가 갖고있는 기능들이 굳이 객체를 생성하지 않고도 쓸 수 있는 기능들이었기 때문입니다.
예를들어 Person객체는 객체 마다 가져야하는 이름, 나이와 같은 멤버변수값들이 있지만, Calculator클래스는 필요한 멤버변수가 없기 때문에 굳이 객체가 생성되지 않더라도 calculate, add와 같은 기능들이 모두 동작할 수 있습니다. 따라서 오히려 이 메소드들이 객체에 종속된다면 객체가 생성될 때마다 불필요하게 메모리에 중복적으로 올라간다고 생각되어서 static으로 선언을 해보았습니다..

static으로 올리면 객체를 생성하지 않아도 메모리에 다 올라온다는 것은 처음 안 사실이네요!! 

> 추가로, static 변수는 프로그램이 실행되고 있는 내내 살아있게 됩니다. 즉, 그 클래스를 이용한 작업을 끝내더라도 static 변수가 점유하고 있는 메모리는 garbage collector(역주: 사용하지 않는 메모리를 회수하는 기능)에 의해서 회수되지 않게 됩니다. 반대로, 프로그래머가 그 변수를 인스턴스화 해서 main() 함수 내에서 하나의 인스턴스로 생성하게 되면, 그리고 그 인스턴스에게 만번의 함수 호출을 시키게 되면 그 만번의 함수 호출이 끝난 후 인스턴스는 소멸됩니다. 따라서 메모리를 훨씬 절약할 수 있게 됩니다.

출처: https://unabated.tistory.com/entry/왜-자바에서-static의-사용을-지양해야-하는가 [랄라라]

자료를 찾아봤는데 static은 객체지향프로그래밍 관점에 맞지 않다네요! 앞으로 지양하겠습니다~

2020-10-20 07:10 UTC, chaeppy commented on src/main/kotlin/calculator/Calculator.kt
> +    companion object {
@l2hyunwoo 
static은 쓰지 않게되었지만 접근제어자는 걸겠습니다 !! 감사합니다 ~

2020-10-20 07:11 UTC, chaeppy commented on src/main/kotlin/calculator/Calculator.kt
> +        }
맞아요 예외가 뜨기는 하더라구요 ~~!! 그래도 던져는줘봤습니다 ㅎㅎ

2020-10-20 07:13 UTC, chaeppy commented on src/main/kotlin/calculator/Calculator.kt
> +        }
@nightmare73 
스트링이나 익스프레션에 대한 것이라고 구체적으로 쓰면 될까요??
@현우씨 
오 감사합니다 ~~ readLine()에 대해서 잘 몰랐네요 감사합니다!

2020-10-20 07:14 UTC, chaeppy commented on src/main/kotlin/calculator/Calculator.kt
> +        }
감사합니다><

2020-10-20 07:15 UTC, chaeppy commented on src/main/kotlin/calculator/Calculator.kt
> +        }
음~~ 고민해보겠습니다 감사합니다!

2020-10-20 07:15 UTC, chaeppy commented on src/main/kotlin/calculator/Calculator.kt
> +    }
감사합니다 ~~ 고민해보겠습니다

2020-10-20 07:15 UTC, chaeppy commented on src/test/kotlin/CalculatorTest.kt
> +    }
감사함다 !

2020-10-20 07:16 UTC, chaeppy commented on src/main/kotlin/calculator/Calculator.kt
> +            }
when절에서 바로 return을 하려다보니 이렇게됐네욥..ㅎㅎㅎㅎ 수정해보겠스빈다!

2020-10-20 07:33 UTC, chaeppy commented on src/main/kotlin/calculator/Calculator.kt
> +        }
@l2hyunwoo 
현우씨 찾아보니까 readLine()반환형이 String? 이라서 써줘야할 것 같은데 ㅠㅠ ""이 넘어오는 경우는 엔터를 쳤을 때 아닐까요..??ㅍㅠㅠ

2020-10-20 08:28 UTC, nightmare73 commented on src/main/kotlin/calculator/Calculator.kt
> +    companion object {
오 아주 좋은 관점이야. 객체가 불변이기 때문에 static으로 올리는 거. 틀린게 아냐! 이것도 좋은 패턴중에 하나야.
이런 의도라면, 현우 말대로 외부에 공개할 것과 공개하지 말아야할 것들에 대해 잘 나누어놔야해.
static이 모두 객체지향과 맞지 않다 라는 말은.. 흠... 좀 위험한거같은데.. 쓰더라도 잘 써야한다 정도? static 덕분에 메모리가 절약되는 구조도 존재하니까. 앞으로 할 내용이기도 하고!

그렇다면 class 보다는 object로 선언해도 좋을거같아.

2020-10-20 08:37 UTC, chaeppy commented on src/main/kotlin/calculator/Calculator.kt
> +    companion object {
@nightmare73 
오 object도 좋은 것 같아요 !!

> 첫째로, static은 객체 지향적이지 않습니다: 개발자들이 static 변수를 ‘악’으로 규정하는 이유는 static 변수가 객체 지향의 패러다임과 상반되기 때문입니다. 특히나 static 변수는, 각 객체의 데이터들이 캡슐화되어야 한다는 객체지향 프로그래밍의 원칙(역주: 한 객체가 가지고 있는 데이터들은 외부에서 함부로 접근하여 수정할 수 없도록 해야 한다는 원칙)에 위반됩니다. 질문자께서 스스로 설명했듯이 static은 스코프(역주: 한 변수가 유효한 범위)를 고려할 필요가 없는 경우, 즉 전역 변수를 사용할 때에 유용합니다. 이는 절차지향적 프로그래밍 혹은 명령형 프로그래밍(역주: C가 대표적인 절차지향적, 명령형 프로그래밍 언어이며 Java 역시 큰 범위에서 절차지향적, 명령형 프로그래밍 언어라고 할 수 있다.)에서 매우 중요한 개념입니다. 하지만 이 것이 객체지향의 관점에서 좋은 코드라고 얘기하기는 힘듭니다. 절차지향 패러다임이 나쁘다는 것이 아닙니다. 다만, 당신의 시니어는 당신이 “객체지향적으로 좋은 코드”를 짜기를 바라는 것입니다. 반대로 당신은 “절차지향적으로 좋은 코드”를 짜기를 원하는 것이라고 말할 수 있을 것입니다.
출처: https://unabated.tistory.com/entry/왜-자바에서-static의-사용을-지양해야-하는가 [랄라라]

자료에서 이렇게 말하더라구요.. ㅎㅎ 또 static의 대안으로 final과 싱글톤 패턴이 있다는데 ~ 참고해서 코드 수정해보도록 하겠습니다!

2020-10-20 08:56 UTC, nightmare73 commented on src/main/kotlin/calculator/Calculator.kt
> +    companion object {
맞아 저쪽엔 지금 불변하지 않는 변하는 것들에 대해서 static이 매우 위험하다고 강조하구있어.
같은 인풋에 대해 무조건 같은 값이 나오는 함수를 순수함수라 부르는데, 그런 함수들만 가지고있다면, static으로 올려도 괜찮아. object가 싱글턴을 만들어줘!

안드로이드에서 많이 쓰던 Glide를 잘생각해보면 좋을거야. Glide() 이렇게 생성해서 쓰지 않잖아 ?

2020-11-01 19:02 UTC, chaeppy commented
## feat(step1): 2차 리팩토링
- 계산 이전에 유효한 식인지 검사하고, 유효하다면 문자를 쪼개주는 SplitString class를 생성했습니다.
- 각 기호에 맞는 계산 전략을 갖고 있는 Operator enum class를 생성했습니다.
- input output view 파일을 생성했습니다.
- 여러가지 올바르지 않은 식에 대한 테스트를 작성했습니다.

2020-11-02 05:46 UTC, nightmare73 approved these changes
고생많았어~~~ 전반적으로 깔끔하고 테스트코드도 설명 잘 적어서 보기 좋습니다
이제 자동차경주를 조져봅시다~~

2020-11-02 05:46 UTC, nightmare73 commented on src/main/kotlin/calculator/SplitString.kt
> +        for (i in splitExpression.indices) {
```suggestion
        for (i in splitExpression.indices step 2) {
```
이런식으로 step N 을 활용해서 2칸씩 옮길수도있어

2020-11-02 05:46 UTC, nightmare73 commented on src/main/kotlin/calculator/Calculator.kt
> +    private val splitString = SplitString
요건 object니까 굳이 갖고있을 필요는 없을거같아

2020-11-02 05:46 UTC, merged