과제 제출합니다~
MalibinStudy/RacingCar pull request #14
Opened 2020-10-18 16:09 UTC by jinsu4755

익숙하지 않아서 그런가...정말 여러번 고치면서도 뭐가 맞는지 모르겠지만...

제출 후에도 객체지향 생활체조 보고 고칠 수 있을 만한곳 찾아서 어떻게 만들어야 좋을까 고민하겠습니다~

2020-10-19 02:28 UTC, nightmare73 requested changes
과제 열심히 하느라 고생했어~~ 😀

전반적으로 코드가 짧고 간결해서 잘 읽혔어. 그래도 이름이나 책임 분리같은걸 중점적으로 더 해봅시다.

한 클래스가 너무 많은 일들을 하고 있어서, 역할을 분리해보자. 다른 사람들 리뷰도 참고하면 좋을거같아. 똑같은 말을 여러명한테 하다보니까 잊어먹고 코멘트 안하는것도 있을거같네..

지금은 "2 3" 입력시에 인덱스 바운드 Exception이 나타나네 리팩터링 해봅시다.

2020-10-19 02:28 UTC, nightmare73 commented on src/main/kotlin/firstweekstringcalculator/StringCalculation.kt
> +) {
계산하고자 하는 입력문자열을 생성자에 집어넣게되면 어떤 문제점들이 생길까?

2020-10-19 02:28 UTC, nightmare73 commented on src/main/kotlin/firstweekstringcalculator/StringCalculation.kt
> +    }
validate를 하는데 무언가를 반환한다? 뭔가 앞뒤가 안맞는거 같아. 검증로직은 검증만 하면 되는데 뭔가 리턴한다고 생각이 들지 않아. 
또, valid는 형용사이기 때문에 일을 하는 메서드에는 어울리지 않다고 생각해. check 내지는 validate처럼 동사를 사용하자.

2020-10-19 02:28 UTC, nightmare73 commented on src/main/kotlin/firstweekstringcalculator/StringCalculation.kt
> +    }
검증을 하는데, split 까지 하는 메서드네. 우선 하는 일이 두가지이고, validate를 하는데 split까지 해줄거라고는 메서드 명만 보고선 알 수 없을거라 생각해. 
또 String은 어떤 String인지 몰라서 더 구체적인 네이밍이 필요하다고봐.

2020-10-19 02:28 UTC, nightmare73 commented on src/main/kotlin/KtlintTest.kt
>  }
이런 프로덕션 코드와 상관없는 코드들은 삭제하는게 좋아.

2020-10-19 02:28 UTC, nightmare73 commented on src/main/kotlin/firstweekstringcalculator/StringCalculation.kt
> +            )
예외처리 굳굳 👍👍 또 뭐가 틀렸는지 알려주는 것도 👍👍 좋은 습관이야.

2020-10-19 02:28 UTC, nightmare73 commented on src/main/kotlin/firstweekstringcalculator/StringCalculation.kt
> +        return when (operator) {
설계를 바꿔서 파라미터를 2개 이하로 줄여보는건 어떨까?

2020-10-19 02:28 UTC, nightmare73 commented on src/main/kotlin/firstweekstringcalculator/StringCalculation.kt
> +    }
이 메서드들은 굳이 래핑하지 않아도 괜찮을거같아!

2020-10-19 02:28 UTC, nightmare73 commented on src/main/kotlin/firstweekstringcalculator/StringCalculation.kt
> +        var result = validOperand(calculateList[0])
result 인데 첫 피연산자 값이 들어간다?
무슨 의도인지는 알겠지만, 네이밍이 적절하진 않아보여.

2020-10-19 02:28 UTC, nightmare73 commented on src/main/kotlin/firstweekstringcalculator/StringCalculation.kt
> +    }
메서드 분리가 잘 되어있어서 계산하는 딱 한가지의 일만 하고있네!
그래서 코드도 짧고 의도가 명확히 보여. 👍

2020-10-19 02:28 UTC, nightmare73 commented on src/main/kotlin/firstweekstringcalculator/StringCalculation.kt
> +    }
이게 Lint에 안걸리다니 흠..

2020-10-19 02:28 UTC, nightmare73 commented on src/main/kotlin/firstweekstringcalculator/StringCalculation.kt
> +    }
딱 메서드명만 두고 봤을 때, 나는 절대 기능 구분을 못할거같아.
* calculateResult()
* calculate()

Result란 말은 불용어 인거같아. https://github.com/MalibinStudy/RacingCar/pull/11#discussion_r507021534

2020-10-19 02:28 UTC, nightmare73 commented on src/test/kotlin/firstweekstringcalculator/StringCalculator.kt
> +        assertThat(resultCalculationString).isEqualTo(10)
```suggestion

        assertThat(stringCalculation.calculateResult()).isEqualTo(10)
```
이건 인라인이 더 나아보여

2020-10-19 02:28 UTC, nightmare73 commented on src/test/kotlin/firstweekstringcalculator/StringCalculator.kt
> +            .hasMessageContaining("입력값이 Null 이거나 공백일 수 없습니다")
```suggestion
        assertThatThrownBy { stringCalculation.calculateResult() }
            .isInstanceOf(IllegalArgumentException::class.java)
            .hasMessageContaining("입력값이 Null 이거나 공백일 수 없습니다")
```
개인적으로 나는 이게 더 나아보여.

2020-10-19 02:28 UTC, nightmare73 commented on src/test/kotlin/firstweekstringcalculator/StringCalculator.kt
> +    }
예외사항 테스트 👍

2020-10-19 08:05 UTC, jinsu4755 commented on src/main/kotlin/firstweekstringcalculator/StringCalculation.kt
> +    }
아 맞아요 처음에는 래핑하지 않았었는데, 궁금한게 사실 그러면 함수안에서 if나 when을 쓰는거 자체가 그 함수가 하는일이 경우에 따라 2~다수 로 바뀌는건 아닌가요?? 사실 이부분이 항상 궁금해서 "함수가 하나의 일을 한다"가... if,when 구문을 사용하면 어떻게 되는것인지, 그럼 이경우는 사실 네이밍을 기똥차게 하는게 답일까요??

2020-10-19 08:06 UTC, jinsu4755 commented on src/main/kotlin/firstweekstringcalculator/StringCalculation.kt
> +    }
저도 사실 많이 고민해봤는데 다른분들 리뷰하면서 어떤 이름을 써야할지 좀더 고민하도록 하겠습니다!!

2020-10-19 08:07 UTC, jinsu4755 commented on src/test/kotlin/firstweekstringcalculator/StringCalculator.kt
> +            .hasMessageContaining("입력값이 Null 이거나 공백일 수 없습니다")
아 이 방법을 생각하지 못했었네요 수정하도록 하겠습니다!

2020-10-19 08:09 UTC, jinsu4755 commented on src/main/kotlin/firstweekstringcalculator/StringCalculation.kt
> +) {
사실 해당 값을 호출되는 메서드에 인자로 넣으려했는데.. 생성자에 들어갈때? 문제점을 잘 모르겠어서 생각좀 해보겠습니다!

2020-10-19 08:10 UTC, jinsu4755 commented on src/main/kotlin/firstweekstringcalculator/StringCalculation.kt
> +    }
해당 부분은 validate하고 그럼 문자열을 나누는 함수로 분리를 해보도록 하겠습니다!

2020-10-19 08:58 UTC, l2hyunwoo commented on src/main/kotlin/firstweekstringcalculator/StringCalculation.kt
> +        return when (operator) {
정수를 정수로 나눌땐 몫이 출력되니까 정확한 값이 출력 안될 것 같아 그 부분 생각해서 operand는 실수형으로 바꾸는 게 좋을 것 같아

2020-10-19 16:27 UTC, malibinYun commented on src/main/kotlin/firstweekstringcalculator/StringCalculation.kt
> +) {
```
class StringCalculation(
    private val calculateString: String?
)
```
이것과
```
class StringCalculation(
    calculateString: String?
)
```
이것의 차이점이 무엇일까?

2020-10-19 16:28 UTC, nightmare73 commented on src/main/kotlin/firstweekstringcalculator/StringCalculation.kt
> +    }
함수가 하나의 일을 한다 라는 말은 사실 어려운말이긴 하지.
추상화 단계에 대해서 생각해보는게 좋을거같아.
물론 위 추상화 단계에서는 "더하기, 빼기, ..." 이지만,
한 단계 위 추상화 단계에서는 "계산하기" 이니까.

2020-10-20 08:52 UTC, chaeppy reviewed
제가 달려고한 코멘트들이 모두 혁님이 이미 말씀하신 것들이라... 코드는 모두 봤습니다 !!! 수고하셨습니다 !!! ^ㅁ^

2020-10-25 14:31 UTC, jinsu4755 commented on src/main/kotlin/firstweekstringcalculator/StringCalculation.kt
> +    }
이부분 파라메터를 어떻게 줄일지 감이 안잡혀서 구조를 어떻게 고치면 좋을지 생각해보고있겠습니다..ㅠ

2020-10-26 03:15 UTC, nightmare73 approved these changes
전반적으로 많이 나아지셨군요.
네이밍이랑 몇 가지 분리에서 아쉽긴하지만 연습하다보면 점차 더 나아질거야.
리팩터링 그만 하려면 머지해달라고 말해줘!

2020-10-26 03:15 UTC, nightmare73 commented on src/main/kotlin/firstweekstringcalculator/Operator.kt
> +                ?: throw IllegalArgumentException("$operatorSymbol 를 연산자로 사용하실 수 없습니다. +, -, *, / 의 연산을 사용해주세요.")
에러 상세 메시지 👍👍

2020-10-26 03:15 UTC, nightmare73 commented on src/test/kotlin/firstweekstringcalculator/StringCalculator.kt
> +            .hasMessageContaining("연산자로 사용하실 수 없습니다. +, -, *, / 의 연산을 사용해주세요.")
```suggestion
        assertThatThrownBy { stringCalculation.calculate(calculationString) }
            .isInstanceOf(IllegalArgumentException::class.java)
            .hasMessage("$ 를 연산자로 사용하실 수 없습니다. +, -, *, / 의 연산을 사용해주세요.")
```
hasMessage를 이용해서 더 정확한 테스트를 진행해보자.

2020-10-26 03:15 UTC, nightmare73 commented on src/main/kotlin/firstweekstringcalculator/ValidateStringCalculation.kt
> +    }
검증을 했는데 입력값이 반환된다? 나는 조금 어색해보여.
검증은 검증만 하는게 좋아!

2020-10-26 03:15 UTC, nightmare73 commented on src/main/kotlin/firstweekstringcalculator/StringCalculation.kt
> +        val validString = validateCalculateString.validateCalculateString(calculateString)
validateCalculateString.validateCalculateString(calculateString).....
네이밍 고민을 좀더 해보는건 어떨까?

2020-10-26 03:15 UTC, nightmare73 commented on src/main/kotlin/firstweekstringcalculator/StringCalculation.kt
> +            accumulator = operation(accumulator, operand, operator)
https://github.com/MalibinStudy/RacingCar/pull/14/files#r511604428
여기에서 해당 코드를 써도 충분할거같아.

2020-10-26 03:15 UTC, nightmare73 commented on src/main/kotlin/firstweekstringcalculator/StringCalculation.kt
> +        }.toDouble()
이게 좀 먼가 아쉽다. 아래에도 똑같은 중복코드가 있기도 하구.
이럴땐 어쩌면 좋을까? 고민 해보고 나중에 물어보면 가르쳐줄게.

2020-11-01 03:18 UTC, nightmare73 commented
오 BigDecimal 사용 굳
전반적으로 깔끔하구만 중간중간 require 로 바꿔보는걸 습관 들여보구 네이밍도 항상 고민을 많이 해봐~~
고생햇습니다 다음미션 합시다

2020-11-01 03:18 UTC, merged