문자열 계산기 코드 구현
MalibinStudy/RacingCar pull request #15
Opened 2020-10-19 05:35 UTC by l2hyunwoo

최대한 깔끔하게 하려고 했는데 어떨지 모르겠네요.

기능 분리를 통해 객체지향적 코드를 작성하려고 노력했습니다.

2020-10-19 06:17 UTC, nightmare73 requested changes
과제하느라 고생했어~~ 하고싶은말은 코멘트 더 달게!

2020-10-19 06:17 UTC, malibinYun commented on src/main/kotlin/stringcalculator/Calculator.kt
> +        for (index in 0..(numberList.size - 1)) {
```suggestion
        for (index in 0 until numberList.size) {
```

2020-10-19 06:17 UTC, malibinYun commented on src/main/kotlin/stringcalculator/Calculator.kt
> +    }
```suggestion
    private fun dequeueNumberList(numberList: MutableList<Double>): Double? {
        return if (numberList.isEmpty()) null
        else numberList.removeAt(0)
    }
```

2020-10-19 06:17 UTC, malibinYun commented on src/main/kotlin/stringcalculator/Calculator.kt
> +    }
메서드 명만 봐서는 뭐하는 애인지 잘 모르겠어. 토큰들을 큐에넣어서 하나씩 빼는 알고리즘이라 이런 메서드가 탄생한걸까..?
큐에 넣고 빼는것 자체가 메서드로 빠져나와있어서 오히려 코드 로직의 의도를 해치는거같아.
val queue = LinkedList<>()
val next = queue.poll()
이런식으로 큐를 사용하는게 일반적인데, 디큐를 하려고 큐를 파라미터로 받고 결과가 나오는게 어색하달까??

2020-10-19 06:17 UTC, malibinYun commented on src/main/kotlin/stringcalculator/Calculator.kt
> +    private val operateNumberCharacterDistinguisher = NumberCharacterDistinguisher()
해당 값들을 클래스 필드로 설정하면 어떤 단점이 있을까?
또, inputExpression 필드의 경우에는 private도 아니고, 뭔가 preprocessingNumberListAndOperatorList을 호출하면 더이상 쓸모가 없어지는거 같은데, 그렇다면 그저 파라미터로 받고 생성자에서 처리하면 되지 않을까?
객체 생성후, preprocessingNumberListAndOperatorList메서드를 외부에서 호출하지 않아주면 이 객체는 제대로 동작하지 않을거라 예상 돼. 과연 이 클래스를 보는 다른 사람들은 이 메서드를 반드시 호출해줘야한다는걸 알까?

2020-10-19 06:17 UTC, malibinYun commented on src/main/kotlin/stringcalculator/Calculator.kt
> +    }
생성자의 역할을 엉뚱한친구가 맡고있어서 결합도가 매우 커지고 응집도가 떨어지는걸로 보여.

2020-10-19 06:17 UTC, nightmare73 commented on src/main/kotlin/stringcalculator/Calculator.kt
> +    }
얘네들은 그냥 래핑하지 않고 써도 좋을거같아.
return 같은 언어의 예약어는 가급적 네이밍에 쓰지 않는게 좋아.

2020-10-19 06:17 UTC, nightmare73 commented on src/main/kotlin/stringcalculator/Calculator.kt
> +        return firstNumber / secondNumber
0으로 나눌 떄의 예외사항 잡은거 굳굳!!👍👍
https://github.com/MalibinStudy/RacingCar/pull/13#discussion_r507343910
이 코멘트 참고해서 생각해봐!

2020-10-19 06:17 UTC, nightmare73 commented on src/main/kotlin/stringcalculator/Calculator.kt
> +        }
배운 require 써보는건 어떨까?
또, 이 메서드에서 너무 많은 일을 도맡아 하고있는거같아.

2020-10-19 06:17 UTC, nightmare73 commented on src/main/kotlin/stringcalculator/Calculator.kt
> +    }
파라미터를 두 개로 줄일 순 없을까?

2020-10-19 06:17 UTC, nightmare73 commented on src/main/kotlin/stringcalculator/NumberCharacterDistinguisher.kt
> +
문자열을 쪼개는 기능을 분리했네! 확실히 어떤 클래스에 어떤 책임들이 부여되어있는지 알 수 있었어. 👍👍
네이밍이좀 아쉬운데, 좀 더 고민해 볼까? https://github.com/MalibinStudy/RacingCar/pull/12#discussion_r507180308

2020-10-19 06:17 UTC, nightmare73 commented on src/main/kotlin/stringcalculator/NumberCharacterDistinguisher.kt
> +    private val regexIsNumber = Regex(pattern = """^[0-9]*${'$'}""")
절대로 바뀌지 않을 상수는 static으로 선언하고, Snake case 모두 대문자가 컨벤션이야. 네이밍은 나라면 아래처럼 했을거같아.

```suggestion
companion object {
    private val NUMBER_REGEX = Regex(pattern = """^[0-9]*${'$'}""")
}
```

2020-10-19 06:17 UTC, nightmare73 commented on src/main/kotlin/stringcalculator/NumberCharacterDistinguisher.kt
> +    }
뮤터블한 객체를 넣고 해당 객체를 리턴한다? 매우 어색해보여. 과연 리턴할 필요가 있을까?
MutableList.sort(), MutableList.sorted() 의 차이에 대해서 한 번 생각해보자.
다른 방법으로 연산자와 숫자를 추출해 낼 수 있을거야.

2020-10-19 06:17 UTC, nightmare73 commented on src/main/kotlin/stringcalculator/NumberCharacterDistinguisher.kt
> +    }
중복코드가 많네! 엔터를 제외하고 거의 같은 코드라 봐도 될거같아

2020-10-19 06:17 UTC, nightmare73 commented on src/main/kotlin/stringcalculator/NumberCharacterDistinguisher.kt
> +        return numberList
numberList 객체에 원소가 추가되는게 아닌, 해당 변수가 계속 갱신되는것 처럼 보이네.
물론 addNumberInList에서 동일 객체를 반환해서 실제로는 그렇지 않겠지만, 과연 해당 메서드를 보지 않은 사람들 또한 그렇게 느낄수 있을까?

2020-10-19 06:17 UTC, nightmare73 commented on src/test/kotlin/TestCode.kt
> +    }
https://github.com/MalibinStudy/RacingCar/pull/14#discussion_r507369010

2020-10-19 06:17 UTC, nightmare73 commented on src/test/kotlin/TestCode.kt
> +}
흠... 이게 린트에 통과했다구...? 믿을수없군... 🤔

2020-10-19 06:22 UTC, nightmare73 commented
"2 3" 입력하면 숫자와 연산자의 수가 안맞다고 나오는데, 이 메세지는 너무 개발한 사람에게 초점이 맞춰진 말인거같아. 다른 협업자가 보려면 좀더 코드를 봐야하는?
나라면, 유효한 수식이 아닙니다. 정도로 했을거같아.

"3 # 4" 이런거에서 #이 연산자가 아니라고 콘솔에 찍어주는게 좋아!

전반적으로 한 메서드가 많은 일을 하는 경우가 많은거같아서 10줄 초과하는게 있었어. 이런 부분들을 위주로 한번 리팩터링 해보자. 중복코드도 없애보구!

2020-10-19 06:41 UTC, l2hyunwoo commented on src/main/kotlin/stringcalculator/Calculator.kt
> +        for (index in 0..(numberList.size - 1)) {
아 고건 제가 몰랐던 내용이에용 감사감사

2020-10-19 07:08 UTC, l2hyunwoo commented on src/test/kotlin/TestCode.kt
> +}
그거 린트에 통과하기 전에 내가 add해서 그런걸거야

2020-10-19 13:27 UTC, l2hyunwoo commented on src/main/kotlin/stringcalculator/Calculator.kt
> +    private val operateNumberCharacterDistinguisher = NumberCharacterDistinguisher()
- 멤버 변수가 많아질수록 책임의 종류?가 많아질 수 있으니까 최대한 줄여서 응집도를 높여야 하는건가? 
- private val로 선언했어야 했는데 그건 깜빡쓰 ㅎㅎ
- preprocessingNumberListAndOperatorList 이 함수도 private fun으로 선언하려고 했어

2020-10-20 12:21 UTC, RoadtoS7 reviewed
현우 과제하느라 고생했어요~~
예외사항마다 Test코드를 적은 부분이 정말 좋은 것 같아👍👍

2020-10-26 02:50 UTC, nightmare73 requested changes
전체적으로 코드 구조 자체가 복잡한거같아. 예를 들면, 계산할 때 널 체크하는 걸 왜 했는지 알기 까지 시간이 어느정도 걸렸어. 구조가 좀 아쉽네.. 😢😢

 또, Operator에 대한 테스트가 부족하네! 더 리팩터링 해보자~~

2020-10-26 02:50 UTC, nightmare73 commented on src/main/kotlin/stringcalculator/Calculator.kt
> +        }
검증 로직은 따로 빼는건 어떨까? require 사용을 습관화 해보자

2020-10-26 02:50 UTC, nightmare73 commented on src/main/kotlin/stringcalculator/Calculator.kt
> +    }
이건 여전히 불필요한 메서드 같아.
Operator.PLUS ->a + b
이런식이 더 나아보여

2020-10-26 02:50 UTC, nightmare73 commented on src/test/kotlin/TestCode.kt
> +            .hasMessageContaining("유효한 수식이 아닙니다.")
인풋은 다르지만 유효한 수식이 아니라는 기능 한 가지에 대한 테스트니,
ParameterizedTest를 사용하는게 어떨까?

2020-10-26 02:50 UTC, nightmare73 commented on src/main/kotlin/stringcalculator/NumberCharacterDistinguisher.kt
> +    fun makeNumberListFirstAndOperatorListSecond(parsedExpression: List<String>): Pair<MutableList<Double>, MutableList<String>> {
컬렉션 내 컬렉션을 넣으면 의미가 흐려진다는 단점이있어.
Pair까진 뭐.. 데이터가 두개가 있다는것 까진 알겠지만, 그 내부의 List 두개가 어떤 데이터를 다루기 위해 넣었던 건지 알 수 없게 된달까? 유지보수성에서 떨어지는거같아.

2020-11-01 03:15 UTC, nightmare73 commented
테스트 코드는 컨벤션 지켜서 만들어주시고!
Parameterized Test도 잘 활용해보고 !
고생햇구 이제 다음미션을 해보자 ㅎㅎ

2020-11-01 03:15 UTC, merged