feat: StringCalulator구현!
MalibinStudy/RacingCar pull request #16
Opened 2020-10-19 08:59 UTC by SONPYEONGHWA

지저분한 코드 많은 피드백 부탁드립니다ㅎㅎ겸허하게 받아들이겠습니다.

2020-10-19 11:42 UTC, CHJUNE-android reviewed
핸드피쓰 화이팅~!

2020-10-19 11:42 UTC, CHJUNE-android commented on src/main/kotlin/CheckString.kt
> +object CheckString {
싱글톤으로 만든 이유가 궁금합니당

2020-10-19 11:42 UTC, CHJUNE-android commented on src/main/kotlin/CheckString.kt
> +        }
```suggestion
        for (i in 1 until eachSplitString step 2) {
                if (!(splitString[i] in operator)) {
                    throw IllegalArgumentException("연산자가 잘못되었습니다.")
                }
        }
```
step 이용하면 해당 숫자만큼 점프하면서 반복가능합니돠

2020-10-19 11:42 UTC, CHJUNE-android commented on src/main/kotlin/CalculateOperator.kt
> +}
main의기능이 StringCalculator의 객체의 readEquation을 호출한다는 것으로 끝나서 살짝 아쉬운 느낌?
주된 플로우가 요약되어 있는 형태라면 좋을 것 같다는 생각이 드네요

2020-10-19 11:42 UTC, CHJUNE-android commented on src/main/kotlin/StringCalculator.kt
> +        val input = scanner.nextLine()
요거 readLine()으로 한방에 해결 가능하답니다

2020-10-19 11:42 UTC, CHJUNE-android commented on src/main/kotlin/StringCalculator.kt
> +            }
이 부분도 for문에 step 2 넣어주면 인덴트 하나 없앨 수 있을듯!

result += splitString[i + 1].toInt()

2020-10-19 16:51 UTC, nightmare73 requested changes
과제 하느라 고생많았어~~~
운동하랴 머하랴 하느라 이제야 리뷰해줬네 미안해 ㅠㅠ
너무 졸려가지구.. 리뷰에 이야기 많이 달아놨어! 좀 더 힘내서 고쳐보자~~

2020-10-19 16:51 UTC, nightmare73 commented on src/main/kotlin/CheckString.kt
> +object CheckString {
딱 "검증" 하는 로직만 빠져나온 객체인거같아. 
https://github.com/MalibinStudy/RacingCar/pull/11#discussion_r507884790 요걸 한 번 참고해서 읽어보는게 좋을거같아.
무엇을 위해 하는 검증인가?
그렇다면 그것에 붙어있어야 하는 검증이지 않을까?

2020-10-19 16:51 UTC, nightmare73 commented on src/main/kotlin/CheckString.kt
> +object CheckString {
또, 네이밍이 "어떤" String을 Check 하는지 모르겠어. 더 구체적으로 지어야할거같아.

2020-10-19 16:51 UTC, nightmare73 commented on src/main/kotlin/CheckString.kt
> +        }
평화 자바하다가 코틀린 넘어왔나보구나??
코틀린에서는 equals 쓰지 않고 == " " 해도 괜찮아!
그리고, input은 nullable 타입이 아니기 때문에 isNullOrEmpty() 메서드를 굳이 호출하지 않아도 돼.
또, white space인 " ", "\t" 등등 이런게 조나 많아도 String.isBlank() 확장함수를 쓰면 해당 문자열이 "공백열" 인지 알 수 있어

2020-10-19 16:51 UTC, nightmare73 commented on src/main/kotlin/CheckString.kt
> +        for (i in eachSplitString) {
```suggestion
        for (i in splitString.indices) {
```
이건 인라인으로 써도 가독성을 해치지 않을거같아.

2020-10-19 16:51 UTC, nightmare73 commented on src/main/kotlin/CheckString.kt
> +            }
인덴트 초과!! 더 분리해보자. 
또, 배운 require를 사용해보자.

2020-10-19 16:51 UTC, nightmare73 commented on src/main/kotlin/StringCalculator.kt
> +        }
```suggestion
        val finalResultNumber = setUpCalculate(splitString)
        if (!checkOperator(splitString)) {
            return false
        }
```
요렇게 쓸수있어! 카멜케이스 지키도록 노력해보자~~

2020-10-19 16:51 UTC, nightmare73 commented on src/main/kotlin/StringCalculator.kt
> +    }
이 친구들은 래핑하지 않아도 될거같아 !

2020-10-19 16:51 UTC, nightmare73 commented on src/test/kotlin/CalculatorTestCode.kt
> +    }
이 테스트는 어떤 의도가 담겨있는지 모르겠어..
계산기에게 계산을 시키기위해 String List를 넘겼는데... true가 나온다는게 테스트코드만 봐서는 이해가 안돼.
테스트코드는 프로덕션 코드의 설명서와도 같은 존재이기에 테스트 하나만 딱 보고도 무슨 동작을 하는지 이해할 수 있게 작성하는게 좋아.

2020-10-19 16:51 UTC, nightmare73 commented on src/main/kotlin/CheckString.kt
> +        val operator = listOf("+", "-", "*", "/")
validation에는 애초에 검증이 안되는 경우 Exception이 발생하기 때문에 리턴값이 필요없어져!

2020-10-19 16:51 UTC, nightmare73 commented on src/main/kotlin/StringCalculator.kt
> +    val checkString = CheckString
result가 클래스 필드로 선언되어있다면 어떤 단점이 생길까?

CheckString은 필드값으로 갖고 있지 않아도 될거같아. 이걸 사용하는 애들은 해당 객체에서 바로 접근해서 써도 될거같아.

2020-10-19 16:51 UTC, nightmare73 commented on src/main/kotlin/StringCalculator.kt
> +    fun setUpCalculate(splitString: List<String>): Int {
fun calculate와 이 메서드명만 비교해서는 어떤게 실제 계산에 쓰이는지 모를거같아.

2020-10-19 16:51 UTC, nightmare73 commented on src/main/kotlin/StringCalculator.kt
> +            }
https://github.com/MalibinStudy/RacingCar/pull/11#discussion_r507885797
요걸 참고해보자~~

2020-10-20 06:22 UTC, SONPYEONGHWA commented on src/main/kotlin/CheckString.kt
> +object CheckString {
StringCalculator에서 쉽게 접근할라고 했는데 그냥 클래스로 만드는게 적합한지 여쭙습니다!!!

2020-10-20 06:23 UTC, SONPYEONGHWA commented on src/main/kotlin/CheckString.kt
> +        }
좋은 꿀팁 정말 감사합니다ㅎㅎ

2020-10-20 06:27 UTC, SONPYEONGHWA commented on src/main/kotlin/CalculateOperator.kt
> +}
이것도 한번 다시 고민해보겠습니다 ㅎ

2020-10-20 06:29 UTC, SONPYEONGHWA commented on src/main/kotlin/CheckString.kt
> +        }
자바랑 헷갈렸네요...기초공부 더 열심히 해보겠습니다 ㅎㅎ

2020-10-20 06:30 UTC, SONPYEONGHWA commented on src/main/kotlin/StringCalculator.kt
> +        }
앗 카멜케이스 이런 실수를 ㅋㅋㅋ감사합니당

2020-10-20 06:30 UTC, SONPYEONGHWA commented on src/test/kotlin/CalculatorTestCode.kt
> +    }
조금 더 가독성 높은 테스트 코드를 작성해볼게요~!!

2020-10-20 06:31 UTC, SONPYEONGHWA commented on src/main/kotlin/StringCalculator.kt
> +    fun setUpCalculate(splitString: List<String>): Int {
다시 직관적인 메서드명으로 바꿔보겠슴다!

2020-10-20 06:36 UTC, SONPYEONGHWA commented on src/main/kotlin/StringCalculator.kt
> +    val checkString = CheckString
result가 클래스 필드로 선언되어 있으면 어떤 단점이 생기는지 혹시 알려주시면 잘 숙지하겠습니다!
아 맞네 싱글톤으로 만들어 놓고 왜그랬지ㅋㅋㅋ

2020-10-20 08:49 UTC, SONPYEONGHWA commented on src/main/kotlin/StringCalculator.kt
> +    }
혹시 래핑하지 않아도 된다는 말이 어떤 의미일까요??

2020-10-20 08:59 UTC, nightmare73 commented on src/main/kotlin/StringCalculator.kt
> +    }
그냥 add() 를 쓰는 함수에서 + 를 그대로 써도 될거같다는 말이었어.
a + b 를 add라는 함수로 한 번 감싼거잖아? 그래서 래핑이라는 말을 써!

2020-10-20 10:05 UTC, RoadtoS7 reviewed
메서드도 하나의 일만 하게끔 잘 짜져 있어서 코드 읽는데 매우 수월했습니다! 
고생했어요~~

2020-10-20 12:02 UTC, nightmare73 requested changes
열시미 리팩터링 하니 뿌듯합니다 계속 나아지고 있으니 조금만 더 해봅시다~~
다음 리팩터링은 내일 가르쳐줄것들 같이 반영하면 좋을거같아!

2020-10-20 12:02 UTC, malibinYun commented on src/main/kotlin/BadCalculateStringCheck.kt
> +object BadCalculateStringCheck {
https://github.com/MalibinStudy/RacingCar/pull/12#discussion_r507180308 요거를 참고해보자

2020-10-20 12:02 UTC, malibinYun commented on src/main/kotlin/BadCalculateStringCheck.kt
> +        require(!input.isBlank()) {
! 이런게 들어가면 한 번 더 해석하게 되는 단점이있어.
그런걸 의식해서 그런지 코틀린에서는 isNotBlank() 라는 메서드도 제공해줘.

2020-10-20 12:02 UTC, malibinYun commented on src/main/kotlin/CalculateOperator.kt
> +    BadCalculateStringCheck.checkBlank(input!!)
!! 는 절대 널일 수 없다는 기호인데, readLine()이 nullable하게 떨어질 수도 있어서 해당 메서드 제작자가 그렇게 만든거지 않을까?
최대한 null safe한 방법으로 코드를 짜는 습관이 좋아. !! 보다는 ?. 접근이라던지 elvis operator 같은걸로 내가 원하는 분기점을 만들어내는거야.

2020-10-20 12:02 UTC, malibinYun commented on src/main/kotlin/StringCalculator.kt
> +    }
핵심 도메인 로직과 View 로직을 분리해보자.
좀더 힌트를 주자면, calculate 메서드를 호출하면 해당 계산 결과를 리턴해주는것이지, View를 찍는 로직을 포함하지 않는거지.

2020-10-20 12:02 UTC, malibinYun commented on src/main/kotlin/CalculateOperator.kt
> +}
메인의 흐름으로 본다면, 인풋을 받아서 검증후에 쪼갠다!
라고 읽히는데, 뭔가 똥싸다 만 느낌이랄까? 네이밍에 좀 더 시간투자를 해봅시다 😊

2020-10-20 12:02 UTC, malibinYun commented on src/test/kotlin/CalculatorTestCode.kt
> +    }
isInstanceOf() 와 hasMessage() 로 어떤 종류의 Exception인지, 어떤 에러 메세지가 나와야 하는지도 테스트 해보자

2020-10-20 12:02 UTC, malibinYun commented on src/test/kotlin/CalculatorTestCode.kt
> +    @Test
테스트에 유효하지 않은 수식이 들어왔을 때, 이상한 연산 기호가 들어왔을 때 등 다양한 예외처리에 대한 테스트가 없는거같아. 더 추가해보면 어떨까?

2020-10-20 12:02 UTC, nightmare73 commented on src/main/kotlin/StringCalculator.kt
> +    }
계산하는 클래스가 문자열을 쪼개는 일 까지 책임을 가지고있어야할까??

2020-10-20 12:11 UTC, SONPYEONGHWA commented on src/main/kotlin/BadCalculateStringCheck.kt
> +object BadCalculateStringCheck {
아하 예시가 너무 좋아서 바로 이해했습니다 ㅎ

2020-10-26 03:34 UTC, nightmare73 approved these changes
전반적으로 코드가 짧아졌네! 계속 나아지는 모습이 아주 좋아요😀
아쉬운점이 몇 가지 있긴 하지만 계속 하다보면 더 나아질거야.
리팩터링 하고싶으면 더 해두되구 멈추고 싶으면 머지하고 싶다고 말해줘!

2020-10-26 03:34 UTC, nightmare73 commented on src/main/kotlin/calculator/OperatorChecker.kt
> +        }
상세 에러메시지 👍👍

2020-10-26 03:34 UTC, nightmare73 commented on src/main/kotlin/calculator/OperatorChecker.kt
> +        }
enum 클래스에서 너무 많은 일을 하고있는거같아.
Operator가 문자열을 분리해야할 책임을 가지고있을까?

2020-10-26 03:34 UTC, nightmare73 commented on src/main/kotlin/calculator/OperatorChecker.kt
> +enum class OperatorChecker(
OperatorChecker가 Operator들을 가지고있는게 조금 어색해보여.
Operator를 find할 때 입력 문자열이 operator인지 검증하는게 이미 포함되어있는건 아닐까?

2020-10-26 03:34 UTC, nightmare73 commented on src/main/kotlin/calculator/view/OutputView.kt
> +}
메서드에 파라미터를 넘기는건 어떨까?
다른 List<String>을 출력하려면 이 객체를 그만큼 만들어야하지 않을까?

2020-10-26 03:34 UTC, nightmare73 commented on src/test/kotlin/CalculatorTestCode.kt
> +
Operator 를 찾는 테스트 등 테스트가 부족해 보이네!
또, 테스트 코드 클래스 자동 생성으로 경로를 맞춰보자.
테스트코드의 클래스명은 "테스트클래스명Test" 가 컨벤션이구, 해당 파일 패키지는 클래스 패키지 경로랑 같아야돼!

2020-10-30 13:45 UTC, merged