[3주차 과제 RacingCar]
MalibinStudy/RacingCar pull request #22
Opened 2020-10-31 03:28 UTC by CHJUNE-android

1급 컬렉션 RacingCar와 RacingCars에 적용
InputView와 ResultView를 나누어 뷰와 로직 구분
RacingZone 테스트코드에서 List를 파라미터로 넘기기 위해 Enum Source를 사용
랜덤 로직 테스트를 위해 TestFactory 사용

2020-11-01 03:51 UTC, nightmare73 requested changes
고생 많으셨습니다.
테스트관련해선 내가 모르는분야가 있어서 코멘트 달기가 어렵군요. 랜덤 테스트에 대해서는 스터디때 알려줄게~~ 리팩토링 해봅시다 💪💪

2020-11-01 03:51 UTC, nightmare73 commented on src/main/kotlin/racingcar/RacingCars.kt
> +        val carList = mutableListOf<RacingCar>()
생성자를 통해서 carList가 빈 mutableList로 초기화가 되는데, prepareCar를 외부에서 부름으로써 한번 더 초기화 되네!
인풋 숫자만큼의 차를 생성하는 코드를 외부에서 한 번 더 호출하게 하는 것보다, 생성자를 통해서 일련의 초기화과정을한꺼번에 진행해보는건 어떨까?

2020-11-01 03:51 UTC, nightmare73 commented on src/main/kotlin/racingcar/RacingCars.kt
> +    }
이 메서드로부터 리턴받은 carList를 가지고 add,remove 연산등을 하게되면 어떻게 될까?

2020-11-01 03:51 UTC, nightmare73 commented on src/main/kotlin/Main.kt
> +    RacingCars().prepareCar(numOfCar)
racingCars에서 prepareCar를 호출하는게 아니라 새로 또 생성해서 하길래 콘솔에 값이 안나오나? 하고 racingCars를 참조하게 바꿔보기도 했는데, 둘다 콘솔에 제대로된 출력이 나오지 않았어.

2020-11-01 03:51 UTC, nightmare73 commented on src/main/kotlin/Main.kt
>  fun main() {
확실히 메인에 핵심 로직들이 흐르듯이 적혀있어서 매우 가독성이 높군요

2020-11-01 03:51 UTC, nightmare73 commented on src/main/kotlin/Main.kt
>  fun main() {
메인 메서드를 가진 파일은 여러개만들수도있어.
그래서 문자열 계산기 했던 메인을 지우지 않고그냥 새로 또 파서 main 만들면 돼.

2020-11-01 03:51 UTC, nightmare73 commented on src/main/kotlin/racingcar/RacingZone.kt
> +}
결과에 대한걸 String으로 붙여서 보내준다는건, 핵심 로직에 뷰 로직이 낑겨있다는 느낌이 들어.
다른 무언가로 결과를 만든 다음에, 그걸 뷰에 넘겨주면 뷰에서 그걸 가지고 뷰를 찍는 방법은 어떨까?

2020-11-01 03:51 UTC, nightmare73 commented on src/main/kotlin/racingcar/RacingCar.kt
> +        }
GoOrNot객체가 불릴때마다 계속 생성되네!

2020-11-01 03:51 UTC, nightmare73 commented on src/main/kotlin/racingcar/GoOrNot.kt
> +class GoOrNot {
만약 요구사항중, 8~10이 나오면 2칸을 전진한다 라는게 추가된다면?
클래스 이름을 바꿔야할거같은 느낌이 들어. 좀 더 현실 세계의 무언가로 은유 또는 추상화 해보는건 어떨까?

2020-11-01 03:51 UTC, nightmare73 commented on src/main/kotlin/racingcar/GoOrNot.kt
> +    }
코틀린 내장 Random을 써보는건 어떨까?

2020-11-01 03:51 UTC, nightmare73 commented on src/test/kotlin/racingcar/RacingZoneTest.kt
> +}
Enum Source를 이용하는 것보다 다른 방법이 있을거같아.
결국 차의 개수랑 시도 수가 변수들인거잖아?
그리구 결론이 조금 이상한거같아. 빈칸이 아닐거라는건 그 테스트 정확하게 테스트를 하지 않는 느낌이랄까

2020-11-01 03:52 UTC, nightmare73 commented
일단은 결과가 콘솔에 제대로 안나오고있어. 메인함수에 문제가 있는줄 알구 바꿔보긴했는데 그래도 출력이 이상하네!
https://github.com/MalibinStudy/RacingCar/pull/11#discussion_r507021534 요거를 참고해보자. List란 말도 불용어중 하나야
전체적으로 뷰 로직을 바깥으로 빼는 작업을 해보자. String으로 핵심 로직 결과를 만드는건 이상해보여!

2020-11-02 01:53 UTC, CHJUNE-android commented on src/main/kotlin/racingcar/RacingCars.kt
> +        val carList = mutableListOf<RacingCar>()
오우... 고런 방법이 있었군요..!

2020-11-02 02:45 UTC, CHJUNE-android commented on src/main/kotlin/racingcar/RacingCars.kt
> +    }
처음 생성했던 객체 내부의 리스트에 대해서 연산이 이뤄지면서 값이 변경될 것 같네요
(가)라는 곳에서 이용하면서 getCurrentCarList해서 그대로 carList를 가져와 수정하게 되면 (나)에서 원하는 carList의 내용이 안나올수도 있을것 같습니다

2020-11-02 02:57 UTC, CHJUNE-android commented on src/main/kotlin/Main.kt
> +    RacingCars().prepareCar(numOfCar)
ResultView를 분리시키면서 대대적으로 뜯어고치게 되었는데 기존 결과랑 달라져버렸네유.. 수정해보겠습니당

2020-11-02 02:58 UTC, CHJUNE-android commented on src/main/kotlin/Main.kt
>  fun main() {
감삼다^__^

2020-11-02 02:58 UTC, CHJUNE-android commented on src/main/kotlin/Main.kt
>  fun main() {
아하 알게씁니다

2020-11-02 06:11 UTC, malibinYun commented on src/main/kotlin/racingcar/OneStepGoOrNot.kt
> +    }
companion object는 구글 놈들 코드를 보면 맨 밑에 쓰더라구
근데 맨 위에 써도 큰 문제는 없다고 하는거같아. Java 스타일이기도 하고.
그래서 취향차이인듯!

2020-11-02 06:11 UTC, malibinYun commented on src/main/kotlin/racingcar/RacingCar.kt
> +) {
여전히 도메인 로직에 View 로직이 끼어있다고봐 String으로 했다는거 자체가
자동차의 거리를 나타내는 "상태" 는 Int로 두고 짜보자

2020-11-02 06:11 UTC, malibinYun commented on src/main/kotlin/racingcar/RacingCars.kt
> +    }
굳이 수정 가능한 MutableList로 리턴할 필요는 없는거같아. 그냥 수정 불가능한 List를 넘겨도, 알아서 넘겨받을 쪽에서 List를 쓰든 그걸 변환해서 Mutable로 바꾸든 할거라 생각해.

2020-11-02 06:11 UTC, malibinYun commented on src/main/kotlin/racingcar/RacingCars.kt
> +    }
생성자의 활용 👍👍👍
for문 대신 repeat()를 써보는건 어떨까?

2020-11-02 06:11 UTC, malibinYun commented on src/main/kotlin/racingcar/RacingZone.kt
> +        return resultOfRace
여전히 개행문자를 붙여준다는 점에서 도메인 로직에 뷰로직이 낑겨있는거같아.
지금 이 자동차경주게임 파일이 콘솔 프로그램이 아니라, 당장 안드로이드로 이 모든 클래스를 옮긴다 했을때, String으로 처리된 모든걸 View로 옮기려면 또 매우 많은 수정 작업을 거쳐야겠지?
마치 라이브러리를 만든다는 생각을 해보는 것도 좋을거같아. 지금 내가 만들고 있는 클래스파일들을 어디다가 포팅을 해도 다른사람들이 이 경주 게임을 이용할 수 있게. (뷰만 그사람이 짠다면)

2020-11-02 06:11 UTC, malibinYun commented on src/main/kotlin/racingcar/RacingZone.kt
> +        return resultOfRace
뷰는 코드가 지저분한 경우가 많다는것도 참고해두면 좋아!

2020-11-02 06:11 UTC, nightmare73 commented on src/main/kotlin/racingcar/OneStepGoOrNot.kt
> +    }
```suggestion
    fun judgeCanGo(): Boolean {
        return createRandomNum() >= MIN_NUM_OF_GO
    }
```
이렇게 쓰는게 좋을듯!

2020-11-02 06:11 UTC, nightmare73 commented on src/main/kotlin/racingcar/RacingCars.kt
> +) {
내부적으로 Car 들을 생성하는데, 이러면 내가 내부 각 RacingCar 객체들을 컨트롤할 수 없게되지 않을까?

2020-11-02 12:10 UTC, l2hyunwoo reviewed
리뷰하면서 진짜 많이 배워갑니다.
불필요한 null 체크와 제 생각 더해서 코멘트 남깁니다. 수고했어 형

2020-11-02 12:10 UTC, l2hyunwoo commented on src/main/kotlin/racingcar/RacingCar.kt
> +    private var carStepList: MutableList<String> = mutableListOf()
carStepList에서 add메서드만 수행을 하는데 val로 선언해도 크게 무리가 없을 것 같아

2020-11-02 12:10 UTC, l2hyunwoo commented on src/test/kotlin/racingcar/RacingCarTest.kt
> +    @TestFactory
와우.....이건 처음봤습니다 따로 공부해볼게요

2020-11-02 12:10 UTC, l2hyunwoo commented on src/main/kotlin/racingcar/RacingCar.kt
> +        return carStepList.toMutableList()
이렇게 쉽게 복사가 가능하다니.....또 배워갑니다...

2020-11-02 12:10 UTC, l2hyunwoo commented on src/main/kotlin/racingcar/ChangeAndCheckNum.kt
> +        } ?: throw IllegalArgumentException("입력값은 null일 수 없습니다.")
입력값 자체에서 NULL이 발생하는 경우는 없는 걸로 알고 있어(입력을 안해도 ""로 넘어감) 여기서 널 체크를 굳이 할 필요는 없을 것 같아.

2020-11-02 12:10 UTC, l2hyunwoo commented on src/main/kotlin/racingcar/RacingCar.kt
> +        }
아래에 혁 형이 말한 것에 대해 조금 더해 생각해보자면 만약에 이걸 GUI 컴포넌트로 옮겼을 때를 가정한다면 출력할 때 "-"가 있는 지 없는 지로 조건문을 짜는 것보다 진리값을 이용해서 짜는게 조금 더 편할 수 있겠지?

2020-11-02 12:10 UTC, l2hyunwoo commented on src/main/kotlin/racingcar/RacingCar.kt
> +    private val oneStepGoOrNot = OneStepGoOrNot()
일급 컬렉션 자료를 참고해서 보자면, 컬렉션 내부의 property는 두지 않는 것을 가정한다고 되어 있어. 이 부분은 함수 내 변수로 선언해도 될 것 같아

2020-11-03 13:22 UTC, RoadtoS7 reviewed
호형 과제 고생했어유~~

2020-11-03 13:22 UTC, RoadtoS7 commented on src/main/kotlin/racingcar/ChangeAndCheckNum.kt
> +            it.toIntOrNull() ?: throw IllegalArgumentException("숫자가 입력되어야 합니다. 입력값: $it")
toIntOrNull()이라는 유용한 함수가 있군요! 배워갑니다~ 👍

2020-11-03 13:22 UTC, RoadtoS7 commented on src/test/kotlin/racingcar/RacingCarTest.kt
> + * 자동차의 상태를 화면에 출력한다. 어느 시점에 출력할 것인지에 대한 제약은 없다. => 계산 즉시 바로 출력 / 계산 다하고 출력
섬세한 요구 사항 분석... 최고... 배워갑니다👍

2020-11-08 06:47 UTC, nightmare73 commented
병원에서 고생이 많으십니다... 이번엔 지각체크 안할게..
다음단계를 위해 빠르게 머지를 때리겠습니다 고생했어유

2020-11-08 06:47 UTC, merged