FEAT(STEP 2): Implementation Without Testing
MalibinStudy/RacingCar pull request #25
Opened 2020-11-02 08:24 UTC by l2hyunwoo

제목을 보면 알다시피 이번 구현에는 테스팅이 거의 들어가 있지 않습니다....
대부분의 함수를 private으로 구현해서 내부 로직에 제가 임의의 입력 값을 줄 수 없다는 것이 너무 큰 문제더군요(그래서 자동차 경주를 시뮬레이팅 해야 테스트가 나올 것 같은데 이게 너무 힘들더라구요). 
- InputView와 ResultView를 구현하여 비즈니스 로직과 입출력을 나누려고 하였습니다.
- 구현 로직은 차 하나의 움직임을 다루는 RacingCar, 전체 차의 움직임을 관장하는 MotorRacing, 차의 움직임을 String Data로 변환하는 CarMovementStorage로 분리했습니다.
- 이외에 구현로직을 용이하게 하는데 랜덤 생성기(RandomNumberGenerator), 검증 로직(InputValidation)을 분리하여 진행했습니다.

리뷰하시는 분들 고생많으십니다... 꾸준히 리팩토링을 하겠습니다.

2020-11-02 10:09 UTC, nightmare73 requested changes
열심히 해주셨군요.
할말이 많아서 코멘트 더 달겠습니다잉

2020-11-02 10:09 UTC, malibinYun commented on src/main/kotlin/racingcar/InputValidation.kt
> +        require(inputValue != 0) { "입력값은 0이 될 수 없습니다." }
0미만의 값을 검증 하는 로직은 과연 이곳에 있는게 맞는걸까?

2020-11-02 10:09 UTC, malibinYun commented on src/main/kotlin/racingcar/InputView.kt
> +            return InputValidation.validateAmountInput(amountOfCars)
validation의 결과를 반환한다?
굉장히 어색해보여. 검증로직은 검증만 할 뿐이라고 생각해

2020-11-02 10:09 UTC, malibinYun commented on src/main/kotlin/racingcar/RacingCar.kt
> +        require(givenRandomNumber in 0..9) { "무작위로 주어진 값이 잘못 설정되었습니다." }
랜덤 값에 대한 validation이 과연 필요할까?
만약 랜덤값 범위 요구사항이 변경된다면, 이곳에서도 또 변경해야할텐데 과연 이 코드를 놓치지않고 수정할 수 있을까?

2020-11-02 10:09 UTC, malibinYun commented on src/main/kotlin/racingcar/TestMain.kt
> +}
도메인 로직과 뷰로직이 매우 강하게 결합되어있네.
만약 이 코드를 그대로 안드로이드에 포팅한다고 생각해보자. 거의 전체를 수정해야하지 않을까?
뭐든 만들때는 항상 라이브러리를 만든다고 생각하고 짜보는 습관이 좋아. 어디든 JVM에서 동작할 수 있는 프로그램이 완벽하지 않을까? 뷰는 당연히 플랫폼마다 다르겠지만 도메인을 처리하는 로직은 플랫폼에 제약을 받지 않는다고 생각해.

2020-11-02 10:09 UTC, malibinYun commented on src/main/kotlin/racingcar/CarMovementStorage.kt
> +
이 클래스가 어떤 책임을 가지고있고 무슨 일을 하는지 잘 모르겠어.

2020-11-02 10:10 UTC, nightmare73 commented
전반적으로 View로직과 Domain 로직이 강하게 결합되어 있는거 같아.

그리고 하는 일이 모양만 조금씩 다르지 중복된 일들을 하는 코드가 많아보여. 코드 구조 자체로 빙글빙글 돌아서 원하는 기능을 하는 느낌이야. 그러지 않고 원하는 일을 확실히 하고 의존성을 줄이도록 노력해보자.

특히 CarMovementStorage 라는 클래스는 무슨일을 하는지 파악하기가 굉장히 힘들어. 메서드명들도 너무 추상화가 안된채로 길기만 한 느낌이라 가독성이 매우 떨어져.

저번에 네이밍에 대해 말했듯이, "가스불 위에 냄비를 올려 물의 온도를 올리기" 보다, "물끓이기" 라는 네이밍이 훨씬 직관적이고 알아보기 쉬운것처럼, 알아보기 쉬운 추상화가 필요해. 변수명이 길어도 좋다 라는 말은 결코 길기만 해도 좋다 라는 말이 아니야.

또, RacingCar가 몇 번 움직일지를 가지고있고, 각 턴에 자신의 발자취를 가지고있게 한거같아. CarMovementStorage는 그 발자취를 또 한번 가공하는것같아. 차라리 View에서 Car를 받아서 그 발자취대로 뷰를 찍는게 더 직관적이지 않을까?

그리고 Car가 그런 상태들을 가지고있어야할까? 만약 요구사항이 n번 레이싱 후에 출력하고 마지막으로 몇턴을 더 달릴지 또한번 입력받고 m번 움직이는것으로 바뀐다면, 이 요구사항에 유연하게 대응할 수 있을까?

우선 가장 중요한 일은 핵심 도메인 로직에서 View에 해당하는 로직들을 분리해내는 일인거같아.



그리고 테스트코드. 

테스트코드를 짤 수 없는 코드는 구조를 의심해보라는 말이 있어. 이 스터디에서 테스트 코드를 짜보라는건 짬으로써 자신의 코드 구조를 의심해보고, 수정하라는 의미야. 다음부턴 무조건 테스트 코드 써서 제출해야해!

2020-11-03 14:59 UTC, chaeppy reviewed
수고하셨습니다!!

2020-11-03 14:59 UTC, chaeppy commented on src/main/kotlin/racingcar/InputView.kt
> +        fun startCarRacing(): MutableList<MutableList<Boolean>> {
레이싱을 시작하는 함수가 레이싱결과까지 반환하는 것 보다는 두개를 분리해주면(?) 혹은 함수이름을 바꾸면?? 쫌 더 좋을 것 같다는 생각이 듭니다!!

2020-11-03 14:59 UTC, chaeppy commented on src/main/kotlin/racingcar/RandomNumberGenerator.kt
> +    fun sendRandomNumber(): Int {
이 함수를 사용하는 입장에서 봤을땐 send보다는 get이라는 함수명이 낫지 않을까? 생각이 들어요!!

2020-11-03 14:59 UTC, chaeppy commented on src/main/kotlin/racingcar/RacingCar.kt
> +    private val carMotionStatus = MutableList(numberOfAttempts) { true }
혹시 한번 더 감싼 이유를알 수 있을까요??

2020-11-08 05:12 UTC, CHJUNE-android reviewed
고생해쏘 혀누

2020-11-08 05:12 UTC, CHJUNE-android commented on src/main/kotlin/racingcar/CarMovementStorage.kt
> +    private fun reflectLastStatus(amountOfCars: Int, stage: Int) {
메소드나 변수 이름을 더 줄일수는 없을까
짧아도 충분히 의미를 알 만한 이름으로 지어볼 수 있다고 생각되는 부분

2020-11-08 11:19 UTC, merged