RacingCar 과제 제출합니다.
MalibinStudy/RacingCar pull request #26
Opened 2020-11-02 14:20 UTC by jinsu4755

이것저것 열심히 만들어봤는데 테스트를 어떻게 해야할지 몰라서 방황하다...
결국 리펙토링 몇번 해보지도 못하고 올립니다ㅠㅠ
뭔가 초기 테스트코드를 만들때 생각과 너무 다른 결과물이 나와서 코드리뷰 받고
더 고쳐보도록하겠습니다!

2020-11-03 05:13 UTC, nightmare73 requested changes

2020-11-03 05:13 UTC, nightmare73 commented on src/main/kotlin/racingcar/Car.kt
> +    }
오 랜덤요소를 밖으로 끄집어내서 메서드를 짤 생각을 하다니 아주 대단하군요
접근은 매우 올바랐으나, 결국 move를 호출함으로써 내부적으로 제어의 흐름이 넘어가는군요.
또, Car 내부에서만 사용되고 Test를 위해 public으로 열어놓는건 좋지 않아.
그래도 접근은 좋았어 👍

2020-11-03 05:13 UTC, nightmare73 commented on src/main/kotlin/racingcar/view/RacingResult.kt
> +            printCarMovingResult(carInTrack.getMovementDistance())
View 로직에서 가장 중요한 도메인 로직인 차를 움직이는로직이 들어가있네.
View와 도메인로직을 분리해보자.

2020-11-03 05:13 UTC, nightmare73 commented on src/test/kotlin/racingcar/CarTest.kt
> +    }
다이나믹 테스트 없이 그냥 Car를 생성하고 그 Car의 movingController에 랜덤값을 집어넣는것과 어떤 차이점이 있는지 모르겠어.

2020-11-03 05:13 UTC, nightmare73 commented on src/test/kotlin/racingcar/RacingCarTracksTest.kt
> +            .isEqualTo(3)
numberOfTrack 이 변수를 가지고 만들었으니 마지막 비교도 해당 변수로 하는게 좀더 맞지 않을까?

2020-11-03 05:13 UTC, nightmare73 commented on src/test/kotlin/racingcar/RacingCarTracksTest.kt
> +    }
이건 너무 당연한 문법적인 부분이라 불필요한 테스트인거같아.

2020-11-03 05:13 UTC, nightmare73 commented on src/main/kotlin/racingcar/Car.kt
> +    }
차라리 movementDistance의 private를 풀고 밑에 private set을 붙이는 건 어떨까

2020-11-03 05:13 UTC, nightmare73 commented on src/main/kotlin/racingcar/RacingCarTracks.kt
> +            racingCarsOnTheTrack.add(car)
repeat()를 써보는건 어떨까?

2020-11-03 05:13 UTC, nightmare73 commented on src/main/kotlin/racingcar/RacingCarTracks.kt
> +            racingCarsOnTheTrack.add(car)
또, 사용자가 이 객체를 만들고나서 이 메서드를 호출해야만 한다는걸 알까?
생성자를 활용해보는건 어떨까?

2020-11-03 05:13 UTC, nightmare73 commented on src/main/kotlin/racingcar/RacingCarTracks.kt
> +            racingCarsOnTheTrack.add(car)
Car를 내부적으로 생성해주고있네.
내가 제어할 수 없는 Car를 안에서 만들어버리면 내가 RacingCarTracks에 대한 테스트를 짤 수 있을까?

2020-11-03 05:44 UTC, jinsu4755 commented on src/test/kotlin/racingcar/CarTest.kt
> +    }
사실 랜덤에 대해서 어떻게 테스트를 해야할지 몰라서 그냥 인터넷에서 이렇더라 되어있는걸 응용해보려했는데... 결국 테스트 코드 짜고 로직 만들다보니까 결국 다이나믹 테스트의 의미가 사라진듯한 기분입니다ㅠ

2020-11-04 02:07 UTC, SONPYEONGHWA reviewed
진수야 넌 최고야~!!! 고생했어~~

2020-11-08 04:47 UTC, CHJUNE-android reviewed
고생했네영 진수

2020-11-08 11:19 UTC, merged