[step3] 자동차 경주 과제
MalibinStudy/RacingCar pull request #29
Opened 2020-11-08 14:59 UTC by RoadtoS7

저번주 코드리뷰까지 반영하여 해보려고 했습니다.
테스트 코드도 유지보수가 쉽게 짜야한다고 한 걸 염두해서 할려고 했는데 잘 했는지는 잘모르겠습니다ㅠㅠ
RaceRecord내에 기록과 관련된 여러 클래스들을 모아놨는데 
관련성이 있다고 생각하여 두었으나, 분리하는게 나을지 궁금합니다!
그럼 이번주도 코드리뷰 부탁드립니다~!!

2020-11-08 16:10 UTC, nightmare73 requested changes
고생하셨습니다~~ 리팩토링 계속 해봅시다

2020-11-08 16:10 UTC, malibinYun commented on src/main/kotlin/racingcar/Car.kt
> +        private set
이름은 한 번 받고 다시는 변경되지 않을 값인거같은데 var로 한 이유가 있을까?

2020-11-08 16:10 UTC, malibinYun commented on src/main/kotlin/racingcar/Car.kt
> +    }
생성자는 필드 값 다음으로 오는게 컨벤션이야.
이 생성자를 호출하지 않고 Checker만 있는 생성자를 호출 할 수도 있을거같은데, 그럼 차 이름은 없는채로 동작하겠네!

2020-11-08 16:10 UTC, malibinYun commented on src/main/kotlin/racingcar/Car.kt
> +}
이 인터페이스는 따로 파일로 빼는게 더 좋아보여

2020-11-08 16:10 UTC, malibinYun commented on src/main/kotlin/racingcar/Car.kt
> +    }
테스트코드만을 위한 코드는 없어야해.

2020-11-08 16:10 UTC, malibinYun commented on src/main/kotlin/racingcar/Cars.kt
Cars를 생성하고 add라는 메서드롤 호출해야만 하는걸 사용자들은 알까?
이 두 행위를 생성자 하나로 충분히 묶을 수 있을거같아.

2020-11-08 16:10 UTC, malibinYun commented on src/main/kotlin/racingcar/Race.kt
> +        return raceRecord
기록이 자동차를 받아서 기록한다.
나는 이 행위가 좀 역전된 느낌이 들어. 차라리 차가 움직일 때 마다 그 때의 Record를 차들이 만들어내는게 더 자연스럽지 않을까?

2020-11-08 16:10 UTC, malibinYun commented on src/main/kotlin/racingcar/RaceRecord.kt
> +class RaceRecord {
1개의 클래스는 1개의 파일에 넣는걸 지향해줘.
물론 Java 스타일인 방법이긴 하지만, 한 파일안에 여러 클래스들이 있는 패턴은 라이브러리쪽에서 정말 추상적인 하나의 주제로 관통할 때 쓰이는거같아. Primitives.kt 같은 파일처럼.

2020-11-08 16:10 UTC, nightmare73 commented on src/main/kotlin/racingcar/RaceRecord.kt
> +    }
이 메서드가 너무 많은 일을 하고있는거 같아.
또, 길기도 해서 가독성이 좀 떨어져서 어떤 기능인지 대충은 알겠지만 잘 와닿지가 않네..

유명한 프로그래머 말로는 람다 안에 3줄이상 쓰지 말라고 하더라구
나는 그래서 람다안에 왠만하면 메서드 하나만 쓰는 편이야

2020-11-08 16:10 UTC, nightmare73 commented on src/main/kotlin/racingcar/RacingCarApplication.kt
> +    }
갑자기 도메인로직이 메인으로 땅겨졌네?!
차들을 만들어내는 기능은 따로 분리해보는건 어떨까?
또, 랜덤 숫자를 뱉는건 Checker를 상속받은 구현체로 만들어보자.

2020-11-08 16:10 UTC, nightmare73 commented on src/test/kotlin/racingcar/CarTest.kt
> +        }
Checker의 로직이 사실상 필요가 없는데 계속 만들어줘야하는 문제가 생겼네. 
어떻게 해결하면 좋을까?

2020-11-08 16:10 UTC, nightmare73 commented on src/test/kotlin/racingcar/CarsTest.kt
>      }
폴더에다가 Ctrl Alt L 시전하면 이런식으로 바뀌는 경우도 있더라구...
나는 가독성을 위해서 폴더에다가 직빵으로 때리는건 지양하는편이야

2020-11-08 16:10 UTC, nightmare73 commented on src/test/kotlin/racingcar/CarTest.kt
>          // given
"달리기 함수 테스트" 라는게 무슨의미일까?
달리기 함수가 뭐하는놈인지 더 구체적으로 설명하는게 좋을거같아.

2020-11-08 16:10 UTC, nightmare73 commented on src/test/kotlin/racingcar/CarsTest.kt
>          }
테스트 코드에서 뭔가 로직이 들어가서는 안돼.
for문, if문 이런게 들어가면 안된다는 의미야.
테스트코드는 설명서이기 때문에 로직이 들어가는 순간 이 코드를 한번 해석해야하는 비용이 발생하게돼. 그래서 모든 코드를 다 박더라도 로직은 없어야해.

2020-11-10 12:39 UTC, RoadtoS7 commented on src/main/kotlin/racingcar/Car.kt
> +}
👍

2020-11-10 12:44 UTC, RoadtoS7 commented on src/main/kotlin/racingcar/Car.kt
> +    }
오옹 컨벤션 기억해두겠습니다!
이번 두번째 과제를 할 때 첫번째 과제때처럼 자동차 이름 없이도 돌아갈 수 있도록 해야하는 것으로 과제를 이해해서요..! 
반드시 자동차 이름이 있어야한다면 없애도록 하겠습니다!

2020-11-10 12:46 UTC, RoadtoS7 commented on src/main/kotlin/racingcar/Cars.kt
제가 이해한 게 맞는지 여쭤보아요! 
Cars(cars: List<Car>) 이런식으로 생성자에서 받는 식을 말씀하시는 거 맞나욥??

2020-11-10 12:51 UTC, RoadtoS7 commented on src/main/kotlin/racingcar/Car.kt
> +        private set
이름 없는 자동차도 가능하도록 하려다 보니 초기값 빈문자열로 주고 나중에 생성자를 통해서 들어온 경우에는 바꾸도록 해야했습니다.
그러다보니 나중에 생성자에서 바꾸기 위해서 var로 할 수 밖에 없었습니다ㅠㅠ

name을 var로 하되, 
외부에서는 name을 참조만 하고, 변경하지 않도록 하기 위해서는 name을 private으로 지정하고 getter를 만드는 방법도 있었지만,
그보다는 private set을 하는 것이 더 코드가 간결한 것 같아서 이렇게 코드를 짜게 되었습니다!

2020-11-10 12:54 UTC, RoadtoS7 commented on src/main/kotlin/racingcar/Race.kt
> +        return raceRecord
오 차들이 record를 만들어내는 것이 맞는 것 같습니다!

2020-11-10 12:58 UTC, RoadtoS7 commented on src/main/kotlin/racingcar/RaceRecord.kt
> +class RaceRecord {
kotlin은 파일내에 클래스로 감싸지 않고도 함수를 둘 수 있는데,
그때 한 파일 내에 관련된 함수를 여러개 두는 거하고 클래스를 여러개 두는 거하고는 다른 문제이겠죠..?
(쓰다보니 클래스는 안되고 함수는 되는 것 같은 느낌적 느낌이 드는데 맞나요??)

2020-11-10 13:01 UTC, l2hyunwoo reviewed
정말 수고 많이했어 역시 실력자의 코드여서 읽어가는 것만으로도 많이 배워가는 것 같아. 내 생각 조금 적었어 참고해줘!

2020-11-10 13:01 UTC, l2hyunwoo commented on src/main/kotlin/racingcar/Car.kt
> +    }
코틀린 스코프 함수 run 하고 함수명이 같아서 개발자들이 보기에는 충분히 헷갈릴 수 있을 것 같은 네이밍이야. 이름을 다른 걸로 바꾸면 더 좋을 것 같아

2020-11-10 13:01 UTC, l2hyunwoo commented on src/main/kotlin/racingcar/RaceRecord.kt
> +        val carRecords = lastRoundRecord.get()
이 두 줄을 잘 합쳐서 
"최종 기록은 전체 라운드 record에서 마지막 라운드의 결과이다"를 표현해서 가져가면 더 가독성이 좋을 것 같아.

`
val finalRecord = roundsRecord.last().getRecord()
`

이런 식으로?

2020-11-10 13:01 UTC, l2hyunwoo commented on src/main/kotlin/racingcar/RaceRecord.kt
> +        }
이 부분은 정렬을 해서 값을 보면 조금 더 쉽게 값을 가져올 수 있었을 것 같은데...
carRecord를 distance로 정렬하고 filter를 통해서 가장 큰 거리를 가진 element들을 filter하는 쪽으로

2020-11-10 13:01 UTC, l2hyunwoo commented on src/main/kotlin/racingcar/RaceRule.kt
>  object RaceRule {
네이밍 좋아용

2020-11-10 13:01 UTC, l2hyunwoo commented on src/main/kotlin/racingcar/Car.kt
> +        }
만약에 차 이름 길이의 수정사항이 발생한다면 놓칠 수 있을 것 같아. 밑에 보면 상수처리 다 잘해줬는데 이 부분은 놓친 것 같아서 기억하라고 코멘트!

2020-11-10 13:01 UTC, l2hyunwoo commented on src/main/kotlin/racingcar/Car.kt
> +        private set
좋은 정보 감사합니다 private....set.....

2020-11-10 13:01 UTC, l2hyunwoo commented on src/main/kotlin/racingcar/view/OutputView.kt
> +            }
```suggestion
           carGraph += "-".repeat(carRecord.distance)
```
인덴팅이 초과된 것 같아!

2020-11-10 13:01 UTC, l2hyunwoo commented on src/test/kotlin/racingcar/CarsTest.kt
>          }
감사합니다 저도 알아갑니다

2020-11-10 13:01 UTC, l2hyunwoo commented on src/test/kotlin/racingcar/CarsTest.kt
> +            })
너도 fun interface가 안 되어서 고통받았니ㅋㅋㅋㅋㅋㅋㅋ

2021-08-12 06:30 UTC, merged