자동차경주 3차과제
MalibinStudy/RacingCar pull request #30
Opened 2020-11-08 15:09 UTC by jinsu4755

도메인에서 결과 뷰를 어떻게 분리해야할까요...ㅠ

map이나 filter같은 자바 Stream관련된 확장함수 배워서 처음 써봤습니다. it대신 안에 들어가는게 뭐인지 열심히 표기했습니다..

2020-11-08 16:46 UTC, nightmare73 requested changes
고생했습니다 TDD는 원래 어려운겁니다.
나는 개인적으로 it 쓰는건 나쁘지 않다고 봅니다
리팩터링 ㄱㄱ 해봅시다

2020-11-08 16:46 UTC, nightmare73 commented on src/main/kotlin/racingcar/Car.kt
>      }
require 내부를 보면 람다를 toString으로 바꾸고 Exception 안에 넣는단다.
람다에는 스트링만 써줘도 충분해

2020-11-08 16:46 UTC, nightmare73 commented on src/main/kotlin/racingcar/Car.kt
> +        private set
생성자를 통한 검증 👍👍
필드가 먼저 오는게 컨벤션이야

2020-11-08 16:46 UTC, nightmare73 commented on src/main/kotlin/racingcar/Car.kt
>      }
자동차의 길이로 오해할 수 있는 네이밍이라 생각해

2020-11-08 16:46 UTC, nightmare73 commented on src/main/kotlin/racingcar/RacingCarMainApplication.kt
> +    val raceParticipation = RegisterCarInRacingFactory.registerRacingParticipationCars(inputRacingInfo.getCarNames())
네임 좀 더 추상화를 해보자

2020-11-08 16:46 UTC, nightmare73 commented on src/main/kotlin/racingcar/RacingParticipatingCars.kt
> +    }
List\<Car\>가 경주의 상태를 나타내는 값이 맞을까?

2020-11-08 16:46 UTC, nightmare73 commented on src/main/kotlin/racingcar/RacingParticipatingCars.kt
> +    private fun findMostMovingDistanceOfCar() = participatingCars.map { car -> car.movementDistance }.maxOrNull()
나라면 getMaxDistance() 정도로 했을거같아

2020-11-08 16:46 UTC, nightmare73 commented on src/main/kotlin/racingcar/RacingCarTracks.kt
> +        RacingResult().showRacingWinner(racingParticipatingCars.getRacingWinner())
여기에 뷰로직이 낑겨있군요. 심지어 뷰를 찍을때마다 뷰를 새로 생성해서 찍고있네.

레이싱 경기를 모두 마치면 해당 결과가 담긴 객체가 튀어나오고, 그 객체를 읽어서 출력만 시키는 구조는 어떨까?

2020-11-08 16:46 UTC, nightmare73 commented on src/main/kotlin/racingcar/RegisterCarInRacingFactory.kt
> +        )
```suggestion
        val cars = registeredNames.map { name -> Car(name, RacingCarMoveController()) }
        return RacingParticipatingCars(cars)
```
난 이게 더 나은듯? 근데 위에도 나쁘지않아

2020-11-08 16:46 UTC, nightmare73 commented on src/test/kotlin/racingcar/CarTest.kt
> +            .hasMessage("자동차 이름으로 ${Car.MAX_CAR_LENGTH}자를 넘길 수 없습니다. $carName 은/는 ${carName.length} 글자 입니다.")
테스트 긋 👍👍

2020-11-08 16:46 UTC, nightmare73 commented on src/test/kotlin/racingcar/RacingParticipatingCarsTest.kt
> +    fun `참가 자동차들의 각 결과마다의 승자가 잘 뽑히는지 확인`() {
승자가 여러명인 경우에도 테스트를 해야하지 않을까??

2020-11-08 16:46 UTC, nightmare73 commented on src/main/kotlin/racingcar/RacingCarTracks.kt
> +        RacingResult().showRacingWinner(racingParticipatingCars.getRacingWinner())
이 메서드는 테스트가 불가능하네. 아래 글들을 읽어보자.
https://github.com/next-step/kotlin-blackjack/pull/19#discussion_r467931192
https://github.com/next-step/kotlin-blackjack/pull/19#issuecomment-671917909

2020-11-08 17:26 UTC, jinsu4755 commented on src/main/kotlin/racingcar/RacingCarTracks.kt
> +        RacingResult().showRacingWinner(racingParticipatingCars.getRacingWinner())
아 계속 결과를 저장하고 마지막에 저장된걸 뽑아올 수 있게 하면 되겠군요..! 이걸 생각을 못했네...

2020-11-08 17:30 UTC, jinsu4755 commented on src/main/kotlin/racingcar/RacingCarTracks.kt
> +        RacingResult().showRacingWinner(racingParticipatingCars.getRacingWinner())
대략 이해는 갔는데...천천히 읽어보고 피드백 반영해보겠습니다..!

2020-11-10 12:19 UTC, RoadtoS7 commented
오옹 map을 유용하게 쓰신 것 같아요 배워갑니다~ 고생하셨어요!

2020-11-10 12:20 UTC, RoadtoS7 reviewed
오옹 map을 유용하게 쓰신 것 같아요 배워갑니다~ 고생하셨어요!

2020-11-10 12:26 UTC, chaeppy commented on src/main/kotlin/racingcar/Car.kt
> +        private set
오,, 전 입력에서 검증하면되지 car에서 검증할 책임이 있을까..?? 했는데 올바른 car의 name이니까 car에서 검증해주는게 맞나보네요

2020-11-10 12:28 UTC, chaeppy commented on src/main/kotlin/racingcar/RegisterCarInRacingFactory.kt
> +        )
진수씨 map을 아주 잘 쓰시군여..? 나만 repeat forEach 광공이였어.. map이 아주 좋은,, 놈이엿군여 덕분에 배워갑니다

2020-11-10 12:32 UTC, chaeppy reviewed
진수씨의 코드를 보고 제가 코틀린을 활용하지 못하는 멍청이구나 느꼇습니다.
앞으로 맵의고수 진수씨 맵의진수라고 부르겟습니다.

2020-11-10 12:32 UTC, chaeppy commented on src/main/kotlin/racingcar/RacingParticipatingCars.kt
> +    private fun findMostMovingDistanceOfCar() = participatingCars.map { car -> car.movementDistance }.maxOrNull()
진수시...? 맵의 고수시군요.. 전 몰라서 for문 돌렷읍니다... map이 하나씩 뱉어서 그걸 가공한 새로운 배열을 만들어주는놈인가보군여... 배워갑니다.. ㄱㅅㄱㅅ...

2020-11-10 12:32 UTC, chaeppy commented on src/main/kotlin/racingcar/RacingParticipatingCars.kt
> +            .map { car -> car.name }
감동의 맵

2020-11-10 12:32 UTC, chaeppy commented on src/main/kotlin/racingcar/RacingParticipatingCars.kt
> +            .map { car -> car.name }
난 toString... 난바보

2020-11-10 13:12 UTC, jinsu4755 commented on src/main/kotlin/racingcar/RacingParticipatingCars.kt
> +    private fun findMostMovingDistanceOfCar() = participatingCars.map { car -> car.movementDistance }.maxOrNull()
아닙니다 저도..포문 열심히 돌릴뻔해서 코드안에 많은 포문을 보자니 자살각 씨게 뜨는거 같을때 안드전설 킹갓혁님의 플픽코드에서본 map을 찾아보고 필터 소트 이런것도 있어서 써봤읍니다... 원래 포문 돌리는 함수가 있었읍니다...

2021-08-12 06:30 UTC, merged