Chaeppy step3
MalibinStudy/RacingCar pull request #31
Opened 2020-11-08 15:23 UTC by chaeppy

2020-11-09 06:52 UTC, nightmare73 requested changes
전반적으로 테스트코드가 부족하군요... 더 리팩터링을 해봅시다

2020-11-09 06:52 UTC, nightmare73 commented on src/main/kotlin/racingCar/Car.kt
> +}
```suggestion
class Car(
    val name: String,
    private val accelerator: Accelerator
) {
    var distance = 0
        private set

    fun move() {
        if (accelerator.canMove())
            distance++
    }
}
```
코틀린 프로퍼티를 활용해보아요

2020-11-09 06:52 UTC, nightmare73 commented on src/main/kotlin/racingCar/Car.kt
> +}
https://github.com/MalibinStudy/RacingCar/pull/29#discussion_r519443321
한 개의 클래스/인터페이스는 하나의 파일로 빼는건 어떨까?

2020-11-09 06:52 UTC, nightmare73 commented on src/main/kotlin/racingCar/Cars.kt
> +    }
난 개인적으로 Map을 리턴하는게 좀 꺼려져
Map 에는 타입만 명시되어있어서 쓰는 사람 입장에서는 여기에 뭐가들어있는지 모른달까?
다 출력해보고 아 이런게 들어있구나 하고 알수있다고 생각해서 나는 공개 메서드 리턴타입으로는 Map을 잘 쓰지 않는 편이야.

2020-11-09 06:52 UTC, nightmare73 commented on src/main/kotlin/racingCar/RaceGame.kt
> +    }
이 메서드는 합하는게 어떨까?
사용자는 result를 꺼내기위해 race 메서드를 호출해야만 한다는 것을 알까?

2020-11-09 06:52 UTC, nightmare73 commented on src/main/kotlin/racingCar/RaceGame.kt
> +    private lateinit var raceResults: MutableList<Map<String, Int>>
컬렉션 내의 컬렉션은 스터디때도 말했지만 가독성이 매우 떨어져.
원하는 정보들을 의미있는 class로 묶어보는건 어떨까

2020-11-09 06:52 UTC, nightmare73 commented on src/main/kotlin/racingCar/RaceGame.kt
> +    }
아마 시도회수를 0넣으면 터질거같네!

2020-11-09 06:52 UTC, nightmare73 commented on src/main/kotlin/racingCar/RacingCarApplication.kt
> +}
이것두 메인 파일에 들어있을 녀석이 아닌거같아

2020-11-09 06:52 UTC, nightmare73 commented on src/main/kotlin/racingCar/RaceGame.kt
> +class RaceGame {
이녀석에 대한 테스트코드가 없군요

2020-11-09 06:52 UTC, nightmare73 commented on src/test/kotlin/racingCar/CarTest.kt
> +        assertThat(car.getDistance()).isEqualTo(3)
https://github.com/MalibinStudy/RacingCar/pull/29#discussion_r519444844
요걸 참고해보세요

2020-11-09 06:52 UTC, nightmare73 commented on src/test/kotlin/racingCar/CarTest.kt
> +    fun moveFailTest() {
위랑 이 테스트랑 맥락이 비슷한거 같은데, ParameterizedTest를 써보는건 어떨까?

2020-11-10 05:50 UTC, chaeppy commented on src/main/kotlin/racingCar/Car.kt
> +}
넵!

2020-11-10 05:51 UTC, chaeppy commented on src/test/kotlin/racingCar/CarTest.kt
> +        assertThat(car.getDistance()).isEqualTo(3)
> 테스트 코드에서 뭔가 로직이 들어가서는 안돼.
for문, if문 이런게 들어가면 안된다는 의미야.
테스트코드는 설명서이기 때문에 로직이 들어가는 순간 이 코드를 한번 해석해야하는 비용이 발생하게돼. 그래서 모든 코드를 다 박더라도 로직은 없어야해.

앗 그렇군여 감사합니다 !

2020-11-10 06:28 UTC, chaeppy commented on src/test/kotlin/racingCar/CarTest.kt
> +    fun moveFailTest() {
감사합니다 훨씬 깔끔하네욥

2020-11-10 06:31 UTC, chaeppy commented on src/main/kotlin/racingCar/RacingCarApplication.kt
> +}
넵 따로 빼겠습니다. 
근데 보통 예를 들어 car하나를 반환하는 팩토리를 CarFactory라고 하는 것 같은데, 
여러개의 car를 갖고있는 Cars를 반환하는 팩토리는 CarsFactory라고 바꿔야할까요? @nightmare73

2020-11-10 06:32 UTC, chaeppy commented on src/main/kotlin/racingCar/RaceGame.kt
> +    }
그러게요
고민을 했었는데 그게 나을 것 같습니다 ! 감사합니다

2020-11-10 06:42 UTC, chaeppy commented on src/main/kotlin/racingCar/RaceGame.kt
> +    }
raceResults.lastIndex 로 수정했습니답

2020-11-10 06:54 UTC, chaeppy commented on src/main/kotlin/racingCar/Car.kt
> +}
왕 감사합니다 ±±

> val은 불변(immutable)이기 때문에 getter만 생성됩니다.
var은 변하기(mutable) 때문에 setter/getter가 모두 생성됩니다.
getter의 이름은 get + 변수이름 으로 정해집니다. setter의 이름은 set + 변수이름 으로 정해집니다.
isStudent처럼 변수 이름에 is가 붙는다면, getter는 is + (is를 제거한 이름), setter는 set + (is를 제거한 이름) 이 됩니다.
private 변수는 getter/setter가 생성되지 않습니다.

> 외부에서 변수를 변경(set)하지 못하도록 할 수 있습니다. set()을 private으로 선언하면 됩니다. 그럼 private setter가 생성되어 내부에서만 설정할 수 있게 됩니다

2020-11-10 12:02 UTC, chaeppy commented
혹시 그런 기분 느껴보셨나요 .
"조때따"
이것 저것 건드렸는데 오히려 역효과가 난 것 같습니다.
돌고돌아 베베꼬여버린 코드가 된 것 같습니다.
6시간 동안 계속 봤더니 머리가아프네여 
피드백을 통해서 다시 리팩토링 하겠습니다
읽으실 분들 ㅎㅇㅌ ㅎㅎ

2020-11-10 13:40 UTC, l2hyunwoo reviewed
수고하셨습니다! 전반적으로 가독성이 괜찮아서 쉽게 이해할 수 있었던 것 같아

2020-11-10 13:40 UTC, l2hyunwoo commented on src/main/kotlin/racingCar/RacingCarApplication.kt
> +    printGameResult(result)
도메인 로직을 두 단계로 분리시켰네 나도 저런 방식 참고해봐야겠다

2020-11-10 13:40 UTC, l2hyunwoo commented on src/main/kotlin/racingCar/record/CarsRecord.kt
> +        return carsRecord.filter { capturedCar -> capturedCar.distance == max }
kotlin 문법에서 사용하는 max함수하고 변수명이 일치하네...어떤 것에 대한 max인지 findMaxDistance를 통해서 구분은 할 수 있겠지만 네이밍 자체로만 봤을 때는 수정할 필요가 있을 것 같아

2020-11-10 13:40 UTC, l2hyunwoo commented on src/main/kotlin/racingCar/view/OutputView.kt
> +    println()
이렇게 하는 것보다 ""를 NEW_LINE 상수 처리해서
println(NEW_LINE)으로 하는게 코드 보기에는 더 좋을 것 같아

2020-11-10 13:40 UTC, l2hyunwoo commented on src/main/kotlin/racingCar/view/OutputView.kt
> +        println(capturedCar.name + ":" + distanceToLine(capturedCar.distance))
```suggestion
        println("${capturedCar.name} : ${distanceToLine(capturedCar.distance)}")
```
자바 스타일에서 코틀린 스타일로 바꾸기!

2020-11-10 13:40 UTC, l2hyunwoo commented on src/main/kotlin/racingCar/view/SplitString.kt
> +    fun getSplitNames(NamesOfCar: String): List<String> {
변수명은 lowerCamelCase로!
```suggestion
    fun getSplitNames(namesOfCar: String): List<String> {
```

2020-11-10 13:40 UTC, l2hyunwoo commented on src/main/kotlin/racingCar/record/CarsRecord.kt
> +    }
distance 변수를 기준으로 sortby 함수 쓰면 될 것 같아!

2021-08-12 06:30 UTC, merged