3차 과제가 완료되었습니다.
MalibinStudy/RacingCar pull request #32
Opened 2020-11-08 16:10 UTC by l2hyunwoo

우선 뷰와 도메인 로직을 분리하기 위해 도메인에서 String Data를 건드리지 않고 View에서 Boolean을 String으로 바꿔주는 메서드를 생성하였습니다.
또한 interface를 활용하여 random 변수에 대한 테스트를 하기에 용이하게 만들었고 이외의 메서드들도 외부에 변수를 빼내어 주입을 하기 쉽게 설계를 했습니다.

2020-11-08 18:49 UTC, jinsu4755 reviewed
과제 고생 많았어~ 쭉 읽어보고 궁금한점과 리뷰 남겨봤어

2020-11-08 18:49 UTC, jinsu4755 commented on src/main/kotlin/racingcar/ResultView.kt
> +        private fun getRacingResult(resultOfRacing: MutableList<RacingCar>): MutableList<MutableList<Boolean>> {
MutableList<MutableList<Boolean>> 컬랙션안에 컬랙션이 들어있네! 우리 스터디 시간에 배웠던것 처럼 내부에 걸랙션을 래핑하는건 어떨까? 내부의컬랙션이 무엇을 담고있는지 파악하기 힘든거 같아..

2020-11-08 18:49 UTC, jinsu4755 commented on src/main/kotlin/racingcar/RacingCar.kt
> +class RacingCar(private val carName: String, numberOfAttempts: Int, private val movingCondition: MovingCondition) {
이부분은 설계를 바꿔서 생성자를 줄여보는게 어떨까?

2020-11-08 18:49 UTC, jinsu4755 commented on src/main/kotlin/racingcar/MotorRacing.kt
> +        return copyCarList
이렇게 복사해서 값을 던져주는 이유가 있을까..? 내부 racingCars를 그대로 던져주면 밖에서도 변경할 수 있어서 복사하는거 같은데 Mutable로 던져줬을때 어디서 값이 변경되는건가...? 난 복사해간 값이 어디서 더 가공되는건지 모르겠어

2020-11-09 05:59 UTC, nightmare73 commented
않이 컨플릭나면 제ㅐ가 머지를 못하잖아여

2020-11-09 07:13 UTC, nightmare73 requested changes
고생하셨습니다. 리팩터링을 조져봅시다

2020-11-09 07:13 UTC, nightmare73 commented on src/main/kotlin/racingcar/InputView.kt
> +        private fun readIntData() = readLine()?.toInt() ?: throw IllegalArgumentException("Null이 입력으로 들어왔습니다.")
음 글쎄.. string을 넣었을때도 같은 Exception이 발생할텐데 매사자가 오히려 디버깅을 방해하는 걸림돌이될거같아

2020-11-09 07:13 UTC, nightmare73 commented on src/main/kotlin/racingcar/MotorRacing.kt
> +    }
인덴트 초과입니다. 더 좋게 짤수있을겁니다

2020-11-09 07:13 UTC, nightmare73 commented on src/main/kotlin/racingcar/RacingCar.kt
> +    }
List의 크기를 받아서 해당 크기만큼 생성하고, 그곳에 인덱스로 접근한다?
이건 Array를 쓰는것과 뭐가 다른건지 모르겠어. List를 쓰는 장점을 모두 무시한 느낌이랄까?

2020-11-09 07:13 UTC, nightmare73 commented on src/main/kotlin/racingcar/ResultView.kt
> +
이름 순서와 트랙의 순서가 과연 보장된 데이터 타입일까?

2020-11-09 07:13 UTC, nightmare73 commented on src/main/kotlin/racingcar/ResultView.kt
> +
Car를 직접 받는것 보다 결과저장을 위한 중간 역할을 하는 클래스를 두는건 어떨까

2020-11-09 07:13 UTC, nightmare73 commented on src/main/kotlin/racingcar/MotorRacing.kt
> +                    }
무명클래스로 구현체를 넣어주는것 말고, 실제 클래스로 구현체를 만드는 건 어떨까

2020-11-09 07:13 UTC, nightmare73 commented on src/main/kotlin/racingcar/MotorRacing.kt
> +    }
이 클래스는 랜덤에 대해 내가 제어할 수 없는 구조인거같아.

2020-11-09 07:13 UTC, nightmare73 commented on src/main/kotlin/racingcar/TestMain.kt
> +fun main() {
파일이름이 왜 TestMain인가요..?

2020-11-09 07:13 UTC, nightmare73 commented on src/test/kotlin/racingcar/InputValidationTest.kt
> +    }
테스트의 이름과 테스트가 작동하는 결론이 다른 느낌이들어.

2020-11-09 07:13 UTC, nightmare73 commented on src/main/kotlin/racingcar/MotorRacing.kt
> +class MotorRacing(namesOfCar: MutableList<String>, numberOfAttempts: Int) {
테스트코드가 없네요. 작성바랍니다

2020-11-10 12:20 UTC, l2hyunwoo commented on src/main/kotlin/racingcar/ResultView.kt
> +        private fun getRacingResult(resultOfRacing: MutableList<RacingCar>): MutableList<MutableList<Boolean>> {
맞아 그 부분을 수용해서 하려고 했는데 저걸 어떻게 래핑해야할 지 고민이 있었던 것 같아 고민을 해볼게

2020-11-10 12:21 UTC, l2hyunwoo commented on src/main/kotlin/racingcar/MotorRacing.kt
> +        return copyCarList
외부에서 클래스 내의 객체를 전달하는 것만으로도 위험하다고 생각해서 복사된 객체를 던져주는 의도로 설계했어 ^^

2020-11-10 12:22 UTC, l2hyunwoo commented on src/main/kotlin/racingcar/MotorRacing.kt
> +    }
(혼돈) 더 예쁘게 짜겠습니다...

2020-11-10 12:24 UTC, l2hyunwoo commented on src/main/kotlin/racingcar/RacingCar.kt
> +    }
조금 C 스타일로 짠 것 같아 한 번 다시 생각해볼게

2020-11-10 12:25 UTC, l2hyunwoo commented on src/main/kotlin/racingcar/MotorRacing.kt
> +    }
아 맞다 이 부분 수정해야겠네

2020-11-10 12:26 UTC, l2hyunwoo commented on src/main/kotlin/racingcar/TestMain.kt
> +fun main() {
시뮬레이션 하는 곳이어서 Test에다가 main함수 있어서 TestMain

2020-11-10 12:26 UTC, l2hyunwoo commented on src/main/kotlin/racingcar/MotorRacing.kt
> +class MotorRacing(namesOfCar: MutableList<String>, numberOfAttempts: Int) {
옙

2021-08-12 06:29 UTC, merged